"""
facts_en.py
─────────────────────────────────────────────────────────────
Central store for all English facts used by the YouTube Shorts bot.

Each entry is a dict with these fields:
  {
    "id"        : unique int  (never reuse / reorder),
    "text"      : the fact in English (spoken + shown as captions),
    "topic"     : "space" | "aliens" | "animals" | "body" | "earth"
                  (picks the on-screen label and fallback footage),
    "footage"   : English Pexels search term for this fact's background video,
    "status"    : "pending" | "posted"   ← updated by quote_status.py after upload
    "posted_at" : ISO-8601 UTC string, or None
  }

quote_status.py reads and writes the "status" / "posted_at" fields
directly in this file so everything stays in one place — no separate JSON needed.

To add a new fact: append a new dict with a unique id,
status="pending", and posted_at=None.
Facts are never re-posted: once every fact is posted the bot stops
with an error until new facts are added here.
─────────────────────────────────────────────────────────────
"""

DEFAULT_QUOTES = [
    {
        "id": 1,
        "text": "A day on Venus is longer than its whole year.",
        "topic": "space",
        "footage": "venus planet",
        "status": "posted",
        "posted_at": "2026-09-26T08:36:39",
    },
    {
        "id": 2,
        "text": "There are more stars in the universe than grains of sand on every beach on Earth.",
        "topic": "space",
        "footage": "stars space",
        "status": "posted",
        "posted_at": "2026-09-26T08:36:39",
    },
    {
        "id": 3,
        "text": "A single teaspoon of a neutron star would weigh about a billion tons.",
        "topic": "space",
        "footage": "neutron star space",
        "status": "posted",
        "posted_at": "2026-09-26T08:36:39",
    },
    {
        "id": 4,
        "text": "The footprints on the Moon could last for millions of years, because there is no wind to blow them away.",
        "topic": "space",
        "footage": "moon surface",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 5,
        "text": "Sunsets on Mars are blue.",
        "topic": "space",
        "footage": "mars planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 6,
        "text": "In space, two pieces of metal can fuse together just by touching. It's called cold welding.",
        "topic": "space",
        "footage": "outer space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 7,
        "text": "Saturn is less dense than water. In a big enough bathtub, it would float.",
        "topic": "space",
        "footage": "saturn planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 8,
        "text": "Scientists have already found more than five thousand planets outside our solar system.",
        "topic": "aliens",
        "footage": "planet space",
        "status": "posted",
        "posted_at": "2026-09-26T11:18:46",
    },
    {
        "id": 9,
        "text": "Jupiter's moon Europa may hide more water under its ice than all of Earth's oceans combined.",
        "topic": "aliens",
        "footage": "europa moon",
        "status": "posted",
        "posted_at": "2026-09-26T11:18:46",
    },
    {
        "id": 10,
        "text": "Tardigrades, animals smaller than a grain of sand, have survived being exposed to outer space.",
        "topic": "aliens",
        "footage": "microscope",
        "status": "posted",
        "posted_at": "2026-09-26T11:18:46",
    },
    {
        "id": 11,
        "text": "In 1977, a telescope picked up a signal so strange that an astronomer wrote Wow next to it. It has never been explained.",
        "topic": "aliens",
        "footage": "radio telescope",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 12,
        "text": "On Saturn's moon Titan, it rains methane, and there are whole lakes of it.",
        "topic": "aliens",
        "footage": "saturn planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 13,
        "text": "An octopus has three hearts and blue blood.",
        "topic": "animals",
        "footage": "octopus",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 14,
        "text": "Sea otters hold hands while they sleep so they don't drift apart.",
        "topic": "animals",
        "footage": "sea otter",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 15,
        "text": "Crows can remember your face, and they hold grudges for years.",
        "topic": "animals",
        "footage": "crow bird",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 16,
        "text": "A shrimp's heart is in its head.",
        "topic": "animals",
        "footage": "shrimp underwater",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 17,
        "text": "Sharks existed before trees did.",
        "topic": "animals",
        "footage": "shark underwater",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 18,
        "text": "Butterflies taste with their feet.",
        "topic": "animals",
        "footage": "butterfly",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 19,
        "text": "Koala fingerprints are so similar to ours that they could confuse a crime scene.",
        "topic": "animals",
        "footage": "koala",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 20,
        "text": "A group of flamingos is called a flamboyance.",
        "topic": "animals",
        "footage": "flamingo",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 21,
        "text": "You can't tickle yourself, because your brain predicts your own touch.",
        "topic": "body",
        "footage": "people laughing",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 22,
        "text": "Your stomach gets a new lining every few days. Otherwise it would digest itself.",
        "topic": "body",
        "footage": "human body",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 23,
        "text": "You are about one centimeter taller in the morning than at night.",
        "topic": "body",
        "footage": "morning stretch",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 24,
        "text": "Your brain is only two percent of your weight, but it uses about twenty percent of your energy.",
        "topic": "body",
        "footage": "brain",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 25,
        "text": "Babies are born with around three hundred bones. Adults have only two hundred and six.",
        "topic": "body",
        "footage": "baby",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 26,
        "text": "Even identical twins have different fingerprints.",
        "topic": "body",
        "footage": "fingerprint",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 27,
        "text": "The largest desert on Earth is not the Sahara. It's Antarctica.",
        "topic": "earth",
        "footage": "antarctica ice",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 28,
        "text": "The Pacific Ocean is bigger than all of Earth's land put together.",
        "topic": "earth",
        "footage": "pacific ocean",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 29,
        "text": "Lightning strikes the Earth about one hundred times every second.",
        "topic": "earth",
        "footage": "lightning storm",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 30,
        "text": "There is not a single bridge across the Amazon River.",
        "topic": "earth",
        "footage": "amazon river",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 31,
        "text": "Measured from base to peak, the tallest mountain on Earth is not Everest. It's Mauna Kea in Hawaii.",
        "topic": "earth",
        "footage": "hawaii volcano",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 32,
        "text": "A few thousand years ago, the Sahara Desert was green, with lakes and grasslands.",
        "topic": "earth",
        "footage": "sahara desert",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 33,
        "text": "Walking through a doorway can make you forget why you entered the room.",
        "topic": "mind",
        "footage": "open door room",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 34,
        "text": "Just reading about yawning can make you yawn. You might be yawning right now.",
        "topic": "mind",
        "footage": "person yawning",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 35,
        "text": "Within minutes of waking up, you forget most of your dream.",
        "topic": "mind",
        "footage": "sleeping person",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 36,
        "text": "Every time you remember something, your brain slightly rewrites the memory.",
        "topic": "mind",
        "footage": "old photographs",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 37,
        "text": "You will hear your own name in a noisy crowd, even when you are not listening.",
        "topic": "mind",
        "footage": "crowd party",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 38,
        "text": "Your brain can't truly multitask. It just switches between tasks very fast.",
        "topic": "mind",
        "footage": "busy person",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 39,
        "text": "Bananas are berries, but strawberries are not.",
        "topic": "food",
        "footage": "bananas",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 40,
        "text": "Carrots were originally purple.",
        "topic": "food",
        "footage": "carrots",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 41,
        "text": "A quarter of an apple is air. That's why apples float.",
        "topic": "food",
        "footage": "apples water",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 42,
        "text": "Peanuts are not nuts. They are legumes, like beans.",
        "topic": "food",
        "footage": "peanuts",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 43,
        "text": "Honey never spoils. Edible honey has been found in ancient Egyptian tombs.",
        "topic": "food",
        "footage": "honey",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 44,
        "text": "India had no chili peppers until about five hundred years ago. They came from the Americas.",
        "topic": "food",
        "footage": "red chilli",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 45,
        "text": "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
        "topic": "history",
        "footage": "pyramids egypt",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 46,
        "text": "Oxford University is older than the Aztec Empire.",
        "topic": "history",
        "footage": "old university",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 47,
        "text": "Woolly mammoths were still alive when the Great Pyramid was being built.",
        "topic": "history",
        "footage": "snow mountains",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 48,
        "text": "The shortest war in history lasted about thirty eight minutes.",
        "topic": "history",
        "footage": "old ship sea",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 49,
        "text": "Napoleon was not short. He was about average height for his time.",
        "topic": "history",
        "footage": "old painting",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 50,
        "text": "The first computer programmer was a woman, Ada Lovelace, in the eighteen forties.",
        "topic": "history",
        "footage": "old library",
        "status": "pending",
        "posted_at": None,
    },
]
