"""
facts_ml.py
─────────────────────────────────────────────────────────────
Central store for all Malayalam facts used by the YouTube Shorts bot.

Each entry is a dict with these fields:
  {
    "id"        : unique int  (never reuse / reorder),
    "text"      : the fact in Malayalam (spoken + shown as captions),
    "topic"     : "space" | "aliens" | "animals" | "body" | "earth"
                  (picks the on-screen label and fallback footage),
    "footage"   : English Pexels search term for this fact's background video,
    "status"    : "pending" | "posted"   ← updated by quote_status.py after upload
    "posted_at" : ISO-8601 UTC string, or None
  }

quote_status.py reads and writes the "status" / "posted_at" fields
directly in this file so everything stays in one place — no separate JSON needed.

To add a new fact: append a new dict with a unique id,
status="pending", and posted_at=None.
Facts are never re-posted: once every fact is posted the bot stops
with an error until new facts are added here.
─────────────────────────────────────────────────────────────
"""

DEFAULT_QUOTES = [
    {
        "id": 1,
        "text": "നമ്മുടെ സൗരയൂഥത്തിന് പുറത്ത് അയ്യായിരത്തിലധികം ഗ്രഹങ്ങളെ ശാസ്ത്രജ്ഞർ ഇതിനകം കണ്ടെത്തിയിട്ടുണ്ട്.",
        "topic": "aliens",
        "footage": "planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 2,
        "text": "വ്യാഴത്തിന്റെ ഉപഗ്രഹമായ യൂറോപ്പയിലെ മഞ്ഞുപാളിക്കടിയിൽ, ഭൂമിയിലെ എല്ലാ സമുദ്രങ്ങളിലും ഉള്ളതിനേക്കാൾ കൂടുതൽ വെള്ളമുള്ള ഒരു കടൽ ഒളിഞ്ഞിരിപ്പുണ്ട്.",
        "topic": "aliens",
        "footage": "ice",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 3,
        "text": "നിങ്ങളുടെ ശരീരത്തിൽ ഏകദേശം മുപ്പത്തിയേഴ് ലക്ഷം കോടി കോശങ്ങളുണ്ട്.",
        "topic": "body",
        "footage": "human body",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 4,
        "text": "നിങ്ങളുടെ തലച്ചോർ ശരീരഭാരത്തിന്റെ രണ്ട് ശതമാനം മാത്രമാണെങ്കിലും ശരീരത്തിന്റെ ഊർജ്ജത്തിന്റെ ഇരുപത് ശതമാനം ഉപയോഗിക്കുന്നു.",
        "topic": "body",
        "footage": "brain",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 5,
        "text": "ആയിരത്തി തൊള്ളായിരത്തി എഴുപത്തിനാലിൽ മനുഷ്യൻ അന്യഗ്രഹജീവികൾക്കായി ഒരു റേഡിയോ സന്ദേശം അയച്ചു. അത് ലക്ഷ്യസ്ഥാനത്ത് എത്താൻ ഇരുപത്തയ്യായിരം വർഷമെടുക്കും.",
        "topic": "aliens",
        "footage": "radio telescope",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 6,
        "text": "ഭൂമിയുടെ ഭ്രമണവേഗം പതിയെ കുറയുന്നു. അതുകൊണ്ട് ദിവസങ്ങളുടെ നീളം വളരെ ചെറിയ അളവിൽ കൂടിക്കൊണ്ടിരിക്കുന്നു.",
        "topic": "earth",
        "footage": "earth from space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 7,
        "text": "ആൻഡ്രോമിഡ ഗാലക്സി സെക്കൻഡിൽ ഏകദേശം നൂറ്റിപ്പത്ത് കിലോമീറ്റർ വേഗത്തിൽ നമ്മുടെ ഗാലക്സിയുടെ നേരെ നീങ്ങിക്കൊണ്ടിരിക്കുകയാണ്.",
        "topic": "space",
        "footage": "galaxy",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 8,
        "text": "വോയേജർ പേടകത്തിൽ, അന്യഗ്രഹജീവികൾക്കായി ഭൂമിയിലെ ശബ്ദങ്ങളും അമ്പത്തിയഞ്ച് ഭാഷകളിലെ ആശംസകളും അടങ്ങിയ ഒരു സ്വർണ്ണ റെക്കോർഡുണ്ട്.",
        "topic": "aliens",
        "footage": "satellite",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 9,
        "text": "നമ്മുടെ ഗാലക്സിയുടെ നടുവിൽ, സൂര്യനേക്കാൾ നാല്പത് ലക്ഷം മടങ്ങ് പിണ്ഡമുള്ള ഒരു ഭീമൻ തമോഗർത്തമുണ്ട്.",
        "topic": "space",
        "footage": "black hole",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 10,
        "text": "ഒരു ന്യൂട്രോൺ നക്ഷത്രത്തിൽ നിന്ന് ഒരു സ്പൂൺ പദാർത്ഥം എടുത്താൽ, അതിന് ഏകദേശം നൂറുകോടി ടൺ ഭാരമുണ്ടാകും.",
        "topic": "space",
        "footage": "stars",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 11,
        "text": "വ്യാഴത്തിലെ ഗ്രേറ്റ് റെഡ് സ്പോട്ട് എന്ന കൊടുങ്കാറ്റിന് ഭൂമിയേക്കാൾ വലിപ്പമുണ്ട്.",
        "topic": "space",
        "footage": "jupiter",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 12,
        "text": "ബഹിരാകാശത്ത് എത്തുമ്പോൾ ബഹിരാകാശയാത്രികരുടെ ഉയരം അഞ്ച് സെന്റിമീറ്റർ വരെ കൂടാറുണ്ട്.",
        "topic": "space",
        "footage": "astronaut",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 13,
        "text": "സൂര്യനോട് ഏറ്റവും അടുത്തുള്ളത് ബുധനാണെങ്കിലും ഏറ്റവും ചൂടുള്ള ഗ്രഹം ശുക്രനാണ്. അവിടെ താപനില നാനൂറ്റി അറുപത് ഡിഗ്രി സെൽഷ്യസിന് മുകളിലാണ്.",
        "topic": "space",
        "footage": "planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 14,
        "text": "ഭൂമിയിലെ എല്ലാ കടൽത്തീരങ്ങളിലെയും മണൽത്തരികളേക്കാൾ കൂടുതൽ നക്ഷത്രങ്ങൾ പ്രപഞ്ചത്തിലുണ്ട്.",
        "topic": "space",
        "footage": "starry sky",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 15,
        "text": "ശനിയുടെ ഉപഗ്രഹമായ എൻസെലാഡസ് ബഹിരാകാശത്തേക്ക് വെള്ളം ചീറ്റുന്നുണ്ട്. അവിടെ ജീവൻ ഉണ്ടാകാമെന്ന് ശാസ്ത്രജ്ഞർ കരുതുന്നു.",
        "topic": "aliens",
        "footage": "geyser",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 16,
        "text": "രാത്രി ആകാശത്ത് നക്ഷത്രങ്ങളെ നോക്കുമ്പോൾ നിങ്ങൾ കാണുന്നത് അവയുടെ ഭൂതകാലമാണ്. ആ പ്രകാശം വർഷങ്ങൾക്ക് മുമ്പ് പുറപ്പെട്ടതാണ്.",
        "topic": "space",
        "footage": "starry sky",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 17,
        "text": "സൂര്യനുള്ളിൽ പത്തുലക്ഷത്തിലധികം ഭൂമികളെ ഉൾക്കൊള്ളിക്കാം.",
        "topic": "space",
        "footage": "sun",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 18,
        "text": "ചൊവ്വയിലെ ഒളിമ്പസ് മോൺസ് എന്ന അഗ്നിപർവ്വതത്തിന് എവറസ്റ്റിനേക്കാൾ ഏകദേശം രണ്ടര മടങ്ങ് ഉയരമുണ്ട്.",
        "topic": "space",
        "footage": "mars",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 19,
        "text": "ഒരു മിന്നലിന്റെ ചൂട് സൂര്യന്റെ ഉപരിതലത്തേക്കാൾ ഏകദേശം അഞ്ച് മടങ്ങ് കൂടുതലാണ്.",
        "topic": "earth",
        "footage": "lightning",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 20,
        "text": "രണ്ടര ദശലക്ഷം പ്രകാശവർഷം അകലെയുള്ള ആൻഡ്രോമിഡ ഗാലക്സിയെ ഇരുണ്ട രാത്രിയിൽ നഗ്നനേത്രങ്ങൾ കൊണ്ട് കാണാം.",
        "topic": "space",
        "footage": "galaxy",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 21,
        "text": "അന്താരാഷ്ട്ര ബഹിരാകാശ നിലയം ഓരോ തൊണ്ണൂറ് മിനിറ്റിലും ഭൂമിയെ ചുറ്റുന്നു. അതിനാൽ അവിടെയുള്ളവർ ഒരു ദിവസം പതിനാറ് സൂര്യോദയങ്ങൾ കാണുന്നു.",
        "topic": "space",
        "footage": "space station",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 22,
        "text": "ആയിരത്തി തൊള്ളായിരത്തി എഴുപത്തിയേഴിൽ ബഹിരാകാശത്ത് നിന്ന് ഒരു ശക്തമായ റേഡിയോ സിഗ്നൽ ലഭിച്ചു. വൗ സിഗ്നൽ എന്ന് അറിയപ്പെടുന്ന അതിന്റെ ഉറവിടം ഇന്നും ആർക്കും വിശദീകരിക്കാനായിട്ടില്ല.",
        "topic": "aliens",
        "footage": "radio telescope",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 23,
        "text": "തേൻ ഒരിക്കലും കേടാകില്ല. ആയിരക്കണക്കിന് വർഷം പഴക്കമുള്ള ഈജിപ്ഷ്യൻ കല്ലറകളിൽ നിന്ന് കഴിക്കാവുന്ന തേൻ കണ്ടെത്തിയിട്ടുണ്ട്.",
        "topic": "earth",
        "footage": "honey",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 24,
        "text": "നീലത്തിമിംഗലത്തിന്റെ ഹൃദയത്തിന് ഒരു ചെറിയ കാറിന്റെ വലിപ്പമുണ്ട്.",
        "topic": "animals",
        "footage": "whale",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 25,
        "text": "വേനൽക്കാലത്ത് ചൂടുകൊണ്ട് ഇരുമ്പ് വികസിക്കുന്നതിനാൽ ഈഫൽ ടവറിന്റെ ഉയരം പതിനഞ്ച് സെന്റിമീറ്റർ വരെ കൂടും.",
        "topic": "earth",
        "footage": "eiffel tower",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 26,
        "text": "ബഹിരാകാശം പൂർണ്ണമായും നിശബ്ദമാണ്. ശബ്ദം സഞ്ചരിക്കാൻ അവിടെ വായുവില്ല.",
        "topic": "space",
        "footage": "outer space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 27,
        "text": "സൂര്യനിൽ നിന്നുള്ള പ്രകാശം ഭൂമിയിലെത്താൻ ഏകദേശം എട്ട് മിനിറ്റ് എടുക്കും. അതായത് നമ്മൾ കാണുന്നത് എട്ട് മിനിറ്റ് മുമ്പുള്ള സൂര്യനെയാണ്.",
        "topic": "space",
        "footage": "sun",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 28,
        "text": "നമ്മുടെ ക്ഷീരപഥ ഗാലക്സിയിൽ പതിനായിരം കോടിയിലധികം നക്ഷത്രങ്ങളുണ്ട്.",
        "topic": "space",
        "footage": "milky way",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 29,
        "text": "നമുക്ക് നിരീക്ഷിക്കാൻ കഴിയുന്ന പ്രപഞ്ചത്തിന് ഒൻപതിനായിരം കോടിയിലധികം പ്രകാശവർഷം വ്യാസമുണ്ട്.",
        "topic": "space",
        "footage": "universe",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 30,
        "text": "ശുക്രനിലെ ഒരു ദിവസം, അവിടുത്തെ ഒരു വർഷത്തേക്കാൾ നീളമുള്ളതാണ്.",
        "topic": "space",
        "footage": "planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 31,
        "text": "മനുഷ്യന്റെ കണ്ണിന് ഏകദേശം ഒരു കോടി നിറങ്ങൾ തിരിച്ചറിയാൻ കഴിയും.",
        "topic": "body",
        "footage": "human eye",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 32,
        "text": "നീരാളിക്ക് മൂന്ന് ഹൃദയങ്ങളും നീല നിറമുള്ള രക്തവുമുണ്ട്.",
        "topic": "animals",
        "footage": "octopus",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 33,
        "text": "വാഴപ്പഴത്തിൽ ചെറിയ അളവിൽ റേഡിയോ ആക്ടീവ് പൊട്ടാസ്യം ഉണ്ട്. പക്ഷേ അത് ഒട്ടും അപകടകരമല്ല.",
        "topic": "earth",
        "footage": "banana",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 34,
        "text": "ടാർഡിഗ്രേഡ് എന്ന സൂക്ഷ്മജീവിക്ക് ബഹിരാകാശത്തിലെ ശൂന്യതയിൽ പോലും ജീവിച്ചിരിക്കാൻ കഴിയും.",
        "topic": "aliens",
        "footage": "microscope",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 35,
        "text": "നെപ്ട്യൂണിലെ ഒരു വർഷം ഭൂമിയിലെ ഏകദേശം നൂറ്റിയറുപത്തിയഞ്ച് വർഷങ്ങൾക്ക് തുല്യമാണ്.",
        "topic": "space",
        "footage": "planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 36,
        "text": "ചന്ദ്രനിൽ കാറ്റില്ലാത്തതിനാൽ, അവിടെ പതിഞ്ഞ ബഹിരാകാശയാത്രികരുടെ കാൽപ്പാടുകൾ ദശലക്ഷക്കണക്കിന് വർഷങ്ങൾ മായാതെ നിൽക്കും.",
        "topic": "space",
        "footage": "moon",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 37,
        "text": "കേരളത്തിലെ കുട്ടനാട്, സമുദ്രനിരപ്പിന് താഴെ കൃഷി ചെയ്യുന്ന ലോകത്തിലെ വളരെ കുറച്ച് സ്ഥലങ്ങളിൽ ഒന്നാണ്.",
        "topic": "earth",
        "footage": "kerala backwaters",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 38,
        "text": "ഭൂമിയിൽ മരങ്ങൾ ഉണ്ടാകുന്നതിനും മുമ്പേ സ്രാവുകൾ ഉണ്ടായിരുന്നു.",
        "topic": "animals",
        "footage": "shark",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 39,
        "text": "പ്രപഞ്ചത്തിൽ ഇരുപതിനായിരം കോടിയിലധികം ഗാലക്സികൾ ഉണ്ടെന്നാണ് ശാസ്ത്രജ്ഞരുടെ കണക്ക്.",
        "topic": "space",
        "footage": "galaxy",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 40,
        "text": "ശനി ഗ്രഹത്തിന്റെ സാന്ദ്രത വെള്ളത്തേക്കാൾ കുറവാണ്. അത്ര വലിയൊരു കടലുണ്ടെങ്കിൽ ശനി അതിൽ പൊങ്ങിക്കിടക്കും.",
        "topic": "space",
        "footage": "planet",
        "status": "pending",
        "posted_at": None,
    },
]
