"""
facts_en.py
─────────────────────────────────────────────────────────────
Central store for all English facts used by the YouTube Shorts bot.

Each entry is a dict with these fields:
  {
    "id"        : unique int  (never reuse / reorder),
    "text"      : the fact in English (spoken + shown as captions),
    "topic"     : "space" | "aliens" | "animals" | "body" | "earth"
                  (picks the on-screen label and fallback footage),
    "footage"   : English Pexels search term for this fact's background video,
    "status"    : "pending" | "posted"   ← updated by quote_status.py after upload
    "posted_at" : ISO-8601 UTC string, or None
  }

quote_status.py reads and writes the "status" / "posted_at" fields
directly in this file so everything stays in one place — no separate JSON needed.

To add a new fact: append a new dict with a unique id,
status="pending", and posted_at=None.
Facts are never re-posted: once every fact is posted the bot stops
with an error until new facts are added here.
─────────────────────────────────────────────────────────────
"""

DEFAULT_QUOTES = [
    {
        "id": 1,
        "text": "A day on Venus is longer than its whole year.",
        "topic": "space",
        "footage": "venus planet",
        "status": "posted",
        "posted_at": "2026-09-26T08:36:39",
    },
    {
        "id": 2,
        "text": "There are more stars in the universe than grains of sand on every beach on Earth.",
        "topic": "space",
        "footage": "stars space",
        "status": "posted",
        "posted_at": "2026-09-26T08:36:39",
    },
    {
        "id": 3,
        "text": "A single teaspoon of a neutron star would weigh about a billion tons.",
        "topic": "space",
        "footage": "neutron star space",
        "status": "posted",
        "posted_at": "2026-09-26T08:36:39",
    },
    {
        "id": 4,
        "text": "The footprints on the Moon could last for millions of years, because there is no wind to blow them away.",
        "topic": "space",
        "footage": "moon surface",
        "status": "posted",
        "posted_at": "2026-10-02T23:33:05",
    },
    {
        "id": 5,
        "text": "Sunsets on Mars are blue.",
        "topic": "space",
        "footage": "mars planet",
        "status": "posted",
        "posted_at": "2026-10-02T23:33:05",
    },
    {
        "id": 6,
        "text": "In space, two pieces of metal can fuse together just by touching. It's called cold welding.",
        "topic": "space",
        "footage": "outer space",
        "status": "posted",
        "posted_at": "2026-10-02T23:33:05",
    },
    {
        "id": 7,
        "text": "Saturn is less dense than water. In a big enough bathtub, it would float.",
        "topic": "space",
        "footage": "saturn planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 8,
        "text": "Scientists have already found more than five thousand planets outside our solar system.",
        "topic": "aliens",
        "footage": "planet space",
        "status": "posted",
        "posted_at": "2026-09-26T11:18:46",
    },
    {
        "id": 9,
        "text": "Jupiter's moon Europa may hide more water under its ice than all of Earth's oceans combined.",
        "topic": "aliens",
        "footage": "europa moon",
        "status": "posted",
        "posted_at": "2026-09-26T11:18:46",
    },
    {
        "id": 10,
        "text": "Tardigrades, animals smaller than a grain of sand, have survived being exposed to outer space.",
        "topic": "aliens",
        "footage": "microscope",
        "status": "posted",
        "posted_at": "2026-09-26T11:18:46",
    },
    {
        "id": 11,
        "text": "In 1977, a telescope picked up a signal so strange that an astronomer wrote Wow next to it. It has never been explained.",
        "topic": "aliens",
        "footage": "radio telescope",
        "status": "posted",
        "posted_at": "2026-10-03T09:41:09",
    },
    {
        "id": 12,
        "text": "On Saturn's moon Titan, it rains methane, and there are whole lakes of it.",
        "topic": "aliens",
        "footage": "saturn planet",
        "status": "posted",
        "posted_at": "2026-10-03T09:41:09",
    },
    {
        "id": 13,
        "text": "An octopus has three hearts and blue blood.",
        "topic": "animals",
        "footage": "octopus",
        "status": "posted",
        "posted_at": "2026-09-27T13:37:32",
    },
    {
        "id": 14,
        "text": "Sea otters hold hands while they sleep so they don't drift apart.",
        "topic": "animals",
        "footage": "sea otter",
        "status": "posted",
        "posted_at": "2026-09-27T13:37:32",
    },
    {
        "id": 15,
        "text": "Crows can remember your face, and they hold grudges for years.",
        "topic": "animals",
        "footage": "crow bird",
        "status": "posted",
        "posted_at": "2026-09-27T13:37:32",
    },
    {
        "id": 16,
        "text": "A shrimp's heart is in its head.",
        "topic": "animals",
        "footage": "shrimp underwater",
        "status": "posted",
        "posted_at": "2026-10-03T18:59:59",
    },
    {
        "id": 17,
        "text": "Sharks existed before trees did.",
        "topic": "animals",
        "footage": "shark underwater",
        "status": "posted",
        "posted_at": "2026-10-03T18:59:59",
    },
    {
        "id": 18,
        "text": "Butterflies taste with their feet.",
        "topic": "animals",
        "footage": "butterfly",
        "status": "posted",
        "posted_at": "2026-10-03T18:59:59",
    },
    {
        "id": 19,
        "text": "Koala fingerprints are so similar to ours that they could confuse a crime scene.",
        "topic": "animals",
        "footage": "koala",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 20,
        "text": "A group of flamingos is called a flamboyance.",
        "topic": "animals",
        "footage": "flamingo",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 21,
        "text": "You can't tickle yourself, because your brain predicts your own touch.",
        "topic": "body",
        "footage": "people laughing",
        "status": "posted",
        "posted_at": "2026-09-28T15:37:18",
    },
    {
        "id": 22,
        "text": "Your stomach gets a new lining every few days. Otherwise it would digest itself.",
        "topic": "body",
        "footage": "human body",
        "status": "posted",
        "posted_at": "2026-09-28T15:37:18",
    },
    {
        "id": 23,
        "text": "You are about one centimeter taller in the morning than at night.",
        "topic": "body",
        "footage": "morning stretch",
        "status": "posted",
        "posted_at": "2026-09-28T15:37:18",
    },
    {
        "id": 24,
        "text": "Your brain is only two percent of your weight, but it uses about twenty percent of your energy.",
        "topic": "body",
        "footage": "brain",
        "status": "posted",
        "posted_at": "2026-10-04T03:37:50",
    },
    {
        "id": 25,
        "text": "Babies are born with around three hundred bones. Adults have only two hundred and six.",
        "topic": "body",
        "footage": "baby",
        "status": "posted",
        "posted_at": "2026-10-04T03:37:50",
    },
    {
        "id": 26,
        "text": "Even identical twins have different fingerprints.",
        "topic": "body",
        "footage": "fingerprint",
        "status": "posted",
        "posted_at": "2026-10-04T03:37:50",
    },
    {
        "id": 27,
        "text": "The largest desert on Earth is not the Sahara. It's Antarctica.",
        "topic": "earth",
        "footage": "antarctica ice",
        "status": "posted",
        "posted_at": "2026-09-29T04:12:42",
    },
    {
        "id": 28,
        "text": "The Pacific Ocean is bigger than all of Earth's land put together.",
        "topic": "earth",
        "footage": "pacific ocean",
        "status": "posted",
        "posted_at": "2026-09-29T04:12:42",
    },
    {
        "id": 29,
        "text": "Lightning strikes the Earth about one hundred times every second.",
        "topic": "earth",
        "footage": "lightning storm",
        "status": "posted",
        "posted_at": "2026-09-29T04:12:42",
    },
    {
        "id": 30,
        "text": "There is not a single bridge across the Amazon River.",
        "topic": "earth",
        "footage": "amazon river",
        "status": "posted",
        "posted_at": "2026-10-04T22:45:35",
    },
    {
        "id": 31,
        "text": "Measured from base to peak, the tallest mountain on Earth is not Everest. It's Mauna Kea in Hawaii.",
        "topic": "earth",
        "footage": "hawaii volcano",
        "status": "posted",
        "posted_at": "2026-10-04T22:45:35",
    },
    {
        "id": 32,
        "text": "A few thousand years ago, the Sahara Desert was green, with lakes and grasslands.",
        "topic": "earth",
        "footage": "sahara desert",
        "status": "posted",
        "posted_at": "2026-10-04T22:45:35",
    },
    {
        "id": 33,
        "text": "Walking through a doorway can make you forget why you entered the room.",
        "topic": "mind",
        "footage": "open door room",
        "status": "posted",
        "posted_at": "2026-10-01T13:17:19",
    },
    {
        "id": 34,
        "text": "Just reading about yawning can make you yawn. You might be yawning right now.",
        "topic": "mind",
        "footage": "person yawning",
        "status": "posted",
        "posted_at": "2026-10-01T13:17:19",
    },
    {
        "id": 35,
        "text": "Within minutes of waking up, you forget most of your dream.",
        "topic": "mind",
        "footage": "sleeping person",
        "status": "posted",
        "posted_at": "2026-10-01T13:17:19",
    },
    {
        "id": 36,
        "text": "Every time you remember something, your brain slightly rewrites the memory.",
        "topic": "mind",
        "footage": "old photographs",
        "status": "posted",
        "posted_at": "2026-10-05T11:07:30",
    },
    {
        "id": 37,
        "text": "You will hear your own name in a noisy crowd, even when you are not listening.",
        "topic": "mind",
        "footage": "crowd party",
        "status": "posted",
        "posted_at": "2026-10-05T11:07:30",
    },
    {
        "id": 38,
        "text": "Your brain can't truly multitask. It just switches between tasks very fast.",
        "topic": "mind",
        "footage": "busy person",
        "status": "posted",
        "posted_at": "2026-10-05T11:07:30",
    },
    {
        "id": 39,
        "text": "Bananas are berries, but strawberries are not.",
        "topic": "food",
        "footage": "bananas",
        "status": "posted",
        "posted_at": "2026-10-01T23:43:29",
    },
    {
        "id": 40,
        "text": "Carrots were originally purple.",
        "topic": "food",
        "footage": "carrots",
        "status": "posted",
        "posted_at": "2026-10-01T23:43:29",
    },
    {
        "id": 41,
        "text": "A quarter of an apple is air. That's why apples float.",
        "topic": "food",
        "footage": "apples water",
        "status": "posted",
        "posted_at": "2026-10-01T23:43:29",
    },
    {
        "id": 42,
        "text": "Peanuts are not nuts. They are legumes, like beans.",
        "topic": "food",
        "footage": "peanuts",
        "status": "posted",
        "posted_at": "2026-10-06T11:01:33",
    },
    {
        "id": 43,
        "text": "Honey never spoils. Edible honey has been found in ancient Egyptian tombs.",
        "topic": "food",
        "footage": "honey",
        "status": "posted",
        "posted_at": "2026-10-06T11:01:33",
    },
    {
        "id": 44,
        "text": "India had no chili peppers until about five hundred years ago. They came from the Americas.",
        "topic": "food",
        "footage": "red chilli",
        "status": "posted",
        "posted_at": "2026-10-06T11:01:33",
    },
    {
        "id": 45,
        "text": "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
        "topic": "history",
        "footage": "pyramids egypt",
        "status": "posted",
        "posted_at": "2026-10-02T10:17:09",
    },
    {
        "id": 46,
        "text": "Oxford University is older than the Aztec Empire.",
        "topic": "history",
        "footage": "old university",
        "status": "posted",
        "posted_at": "2026-10-02T10:17:09",
    },
    {
        "id": 47,
        "text": "Woolly mammoths were still alive when the Great Pyramid was being built.",
        "topic": "history",
        "footage": "snow mountains",
        "status": "posted",
        "posted_at": "2026-10-02T10:17:09",
    },
    {
        "id": 48,
        "text": "The shortest war in history lasted about thirty eight minutes.",
        "topic": "history",
        "footage": "old ship sea",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 49,
        "text": "Napoleon was not short. He was about average height for his time.",
        "topic": "history",
        "footage": "old painting",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 50,
        "text": "The first computer programmer was a woman, Ada Lovelace, in the eighteen forties.",
        "topic": "history",
        "footage": "old library",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 51,
        "text": "The Sun makes up more than ninety nine percent of all the mass in our solar system.",
        "topic": "space",
        "footage": "sun space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 52,
        "text": "The Moon is slowly drifting away from Earth, about four centimeters every year.",
        "topic": "space",
        "footage": "moon surface",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 53,
        "text": "Astronauts can grow up to five centimeters taller in space, because their spine is no longer squeezed by gravity.",
        "topic": "space",
        "footage": "astronaut space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 54,
        "text": "Jupiter's Great Red Spot is a storm bigger than the whole Earth, and it has been raging for hundreds of years.",
        "topic": "space",
        "footage": "jupiter planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 55,
        "text": "The International Space Station circles the Earth about every ninety minutes, so astronauts see around sixteen sunrises a day.",
        "topic": "space",
        "footage": "space station",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 56,
        "text": "When you look at the stars, you are looking into the past, because their light left them long ago.",
        "topic": "space",
        "footage": "stars space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 57,
        "text": "Some planets outside our solar system are so hot that it may rain molten glass sideways.",
        "topic": "aliens",
        "footage": "planet space",
        "status": "posted",
        "posted_at": "2026-10-03T09:41:09",
    },
    {
        "id": 58,
        "text": "Saturn's moon Enceladus shoots jets of water into space from an ocean hidden under its ice.",
        "topic": "aliens",
        "footage": "saturn planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 59,
        "text": "The Voyager probes carry a golden record with sounds and greetings from Earth, in case aliens ever find them.",
        "topic": "aliens",
        "footage": "space probe",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 60,
        "text": "Mars once had rivers and lakes. Today, scientists are searching its rocks for signs of ancient life.",
        "topic": "aliens",
        "footage": "mars planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 61,
        "text": "Our radio and TV signals have already travelled more than one hundred light years into space.",
        "topic": "aliens",
        "footage": "radio telescope",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 62,
        "text": "Elephants can hear thunderstorms from far away through vibrations in their feet.",
        "topic": "animals",
        "footage": "elephant",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 63,
        "text": "Cows have best friends, and they get stressed when they are separated.",
        "topic": "animals",
        "footage": "cow field",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 64,
        "text": "An owl can't move its eyes, so it turns its head almost all the way around instead.",
        "topic": "animals",
        "footage": "owl",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 65,
        "text": "Dolphins sleep with one half of their brain at a time, so they never fully switch off.",
        "topic": "animals",
        "footage": "dolphins",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 66,
        "text": "A hummingbird's heart can beat more than one thousand times a minute.",
        "topic": "animals",
        "footage": "hummingbird",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 67,
        "text": "A starfish has no brain and no blood.",
        "topic": "animals",
        "footage": "starfish",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 68,
        "text": "Some penguins propose to their partner by offering them the perfect pebble.",
        "topic": "animals",
        "footage": "penguins",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 69,
        "text": "Tooth enamel is the hardest substance in the human body.",
        "topic": "body",
        "footage": "smile teeth",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 70,
        "text": "Your eyes can tell apart about ten million different colors.",
        "topic": "body",
        "footage": "human eye closeup",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 71,
        "text": "Your heart beats about one hundred thousand times every single day.",
        "topic": "body",
        "footage": "heartbeat",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 72,
        "text": "Your liver can regrow itself, even after a large part of it is removed.",
        "topic": "body",
        "footage": "doctor hospital",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 73,
        "text": "Your skin is your largest organ, and you shed thousands of skin cells every minute.",
        "topic": "body",
        "footage": "skin closeup",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 74,
        "text": "Your brain can't feel pain. It has no pain sensors of its own.",
        "topic": "body",
        "footage": "brain",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 75,
        "text": "Russia is so wide that it spans eleven time zones.",
        "topic": "earth",
        "footage": "russia landscape",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 76,
        "text": "The Dead Sea is so salty that you float on it without even trying.",
        "topic": "earth",
        "footage": "dead sea floating",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 77,
        "text": "Some bamboo can grow almost one meter in a single day.",
        "topic": "earth",
        "footage": "bamboo forest",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 78,
        "text": "Some trees alive today are more than four thousand years old.",
        "topic": "earth",
        "footage": "ancient trees",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 79,
        "text": "The coldest temperature ever recorded on Earth was minus eighty nine degrees Celsius, in Antarctica.",
        "topic": "earth",
        "footage": "snow blizzard",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 80,
        "text": "More than eighty percent of the ocean has never been mapped or explored by humans.",
        "topic": "earth",
        "footage": "ocean waves",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 81,
        "text": "Most people have felt deja vu, the strange feeling that this exact moment has happened before.",
        "topic": "mind",
        "footage": "person thinking",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 82,
        "text": "Many people feel their phone vibrate when it didn't. It's called phantom vibration.",
        "topic": "mind",
        "footage": "smartphone",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 83,
        "text": "When a song gets stuck in your head, it's called an earworm.",
        "topic": "mind",
        "footage": "headphones music",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 84,
        "text": "Seeing faces in clouds or walls is called pareidolia. Your brain is wired to find faces everywhere.",
        "topic": "mind",
        "footage": "clouds sky",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 85,
        "text": "Staying awake all night can affect your brain like being drunk.",
        "topic": "mind",
        "footage": "tired person night",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 86,
        "text": "A single strawberry carries about two hundred seeds on its outside.",
        "topic": "food",
        "footage": "strawberries",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 87,
        "text": "Cashew nuts grow on the outside of a fruit called the cashew apple.",
        "topic": "food",
        "footage": "cashew",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 88,
        "text": "Tomatoes were once feared in Europe, because people thought they were poisonous.",
        "topic": "food",
        "footage": "tomatoes",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 89,
        "text": "After water, tea is the most popular drink in the world.",
        "topic": "food",
        "footage": "tea cup",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 90,
        "text": "Chocolate is poisonous to dogs.",
        "topic": "food",
        "footage": "chocolate",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 91,
        "text": "The ancient Romans used concrete that has survived for two thousand years.",
        "topic": "history",
        "footage": "ancient ruins",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 92,
        "text": "Tug of war was once an Olympic sport.",
        "topic": "history",
        "footage": "old map",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 93,
        "text": "The Great Library of Alexandria tried to collect a copy of every book in the world.",
        "topic": "history",
        "footage": "old library",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 94,
        "text": "The Great Pyramid was the tallest building on Earth for almost four thousand years.",
        "topic": "history",
        "footage": "pyramids egypt",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 95,
        "text": "The Eiffel Tower was supposed to be taken down after twenty years.",
        "topic": "history",
        "footage": "old painting",
        "status": "pending",
        "posted_at": None,
    },
]
