"""
facts_ml.py
─────────────────────────────────────────────────────────────
Central store for all Malayalam facts used by the YouTube Shorts bot.

Each entry is a dict with these fields:
  {
    "id"        : unique int  (never reuse / reorder),
    "text"      : the fact in Malayalam (spoken + shown as captions),
    "topic"     : "space" | "aliens" | "animals" | "body" | "earth"
                  (picks the on-screen label and fallback footage),
    "footage"   : English Pexels search term for this fact's background video,
    "status"    : "pending" | "posted"   ← updated by quote_status.py after upload
    "posted_at" : ISO-8601 UTC string, or None
  }

quote_status.py reads and writes the "status" / "posted_at" fields
directly in this file so everything stays in one place — no separate JSON needed.

To add a new fact: append a new dict with a unique id,
status="pending", and posted_at=None.
Facts are never re-posted: once every fact is posted the bot stops
with an error until new facts are added here.
─────────────────────────────────────────────────────────────
"""

DEFAULT_QUOTES = [
    {
        "id": 1,
        "text": "നമ്മുടെ സൗരയൂഥത്തിന് പുറത്ത് അയ്യായിരത്തിലധികം ഗ്രഹങ്ങളെ ശാസ്ത്രജ്ഞർ ഇതിനകം കണ്ടെത്തിയിട്ടുണ്ട്.",
        "topic": "aliens",
        "footage": "planet space",
        "status": "posted",
        "posted_at": "2026-09-26T07:17:31",
    },
    {
        "id": 2,
        "text": "വ്യാഴത്തിന്റെ ഉപഗ്രഹമായ യൂറോപ്പയിലെ മഞ്ഞുപാളിക്കടിയിൽ, ഭൂമിയിലെ എല്ലാ സമുദ്രങ്ങളിലും ഉള്ളതിനേക്കാൾ കൂടുതൽ വെള്ളമുള്ള ഒരു കടൽ ഒളിഞ്ഞിരിപ്പുണ്ട്.",
        "topic": "aliens",
        "footage": "europa moon",
        "status": "posted",
        "posted_at": "2026-09-26T07:17:31",
    },
    {
        "id": 3,
        "text": "നിങ്ങളുടെ ശരീരത്തിൽ ഏകദേശം മുപ്പത്തിയേഴ് ലക്ഷം കോടി കോശങ്ങളുണ്ട്.",
        "topic": "body",
        "footage": "human body",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 4,
        "text": "നിങ്ങളുടെ തലച്ചോർ ശരീരഭാരത്തിന്റെ രണ്ട് ശതമാനം മാത്രമാണെങ്കിലും ശരീരത്തിന്റെ ഊർജ്ജത്തിന്റെ ഇരുപത് ശതമാനം ഉപയോഗിക്കുന്നു.",
        "topic": "body",
        "footage": "brain",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 5,
        "text": "ആയിരത്തി തൊള്ളായിരത്തി എഴുപത്തിനാലിൽ മനുഷ്യൻ അന്യഗ്രഹജീവികൾക്കായി ഒരു റേഡിയോ സന്ദേശം അയച്ചു. അത് ലക്ഷ്യസ്ഥാനത്ത് എത്താൻ ഇരുപത്തയ്യായിരം വർഷമെടുക്കും.",
        "topic": "aliens",
        "footage": "radio telescope",
        "status": "posted",
        "posted_at": "2026-09-26T07:17:31",
    },
    {
        "id": 6,
        "text": "ഭൂമിയുടെ ഭ്രമണവേഗം പതിയെ കുറയുന്നു. അതുകൊണ്ട് ദിവസങ്ങളുടെ നീളം വളരെ ചെറിയ അളവിൽ കൂടിക്കൊണ്ടിരിക്കുന്നു.",
        "topic": "earth",
        "footage": "earth from space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 7,
        "text": "ആൻഡ്രോമിഡ ഗാലക്സി സെക്കൻഡിൽ ഏകദേശം നൂറ്റിപ്പത്ത് കിലോമീറ്റർ വേഗത്തിൽ നമ്മുടെ ഗാലക്സിയുടെ നേരെ നീങ്ങിക്കൊണ്ടിരിക്കുകയാണ്.",
        "topic": "space",
        "footage": "galaxy space",
        "status": "posted",
        "posted_at": "2026-09-25T12:12:44",
    },
    {
        "id": 8,
        "text": "വോയേജർ പേടകത്തിൽ, അന്യഗ്രഹജീവികൾക്കായി ഭൂമിയിലെ ശബ്ദങ്ങളും അമ്പത്തിയഞ്ച് ഭാഷകളിലെ ആശംസകളും അടങ്ങിയ ഒരു സ്വർണ്ണ റെക്കോർഡുണ്ട്.",
        "topic": "aliens",
        "footage": "spacecraft space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 9,
        "text": "നമ്മുടെ ഗാലക്സിയുടെ നടുവിൽ, സൂര്യനേക്കാൾ നാല്പത് ലക്ഷം മടങ്ങ് പിണ്ഡമുള്ള ഒരു ഭീമൻ തമോഗർത്തമുണ്ട്.",
        "topic": "space",
        "footage": "black hole space",
        "status": "posted",
        "posted_at": "2026-09-25T12:12:44",
    },
    {
        "id": 10,
        "text": "ഒരു ന്യൂട്രോൺ നക്ഷത്രത്തിൽ നിന്ന് ഒരു സ്പൂൺ പദാർത്ഥം എടുത്താൽ, അതിന് ഏകദേശം നൂറുകോടി ടൺ ഭാരമുണ്ടാകും.",
        "topic": "space",
        "footage": "stars space",
        "status": "posted",
        "posted_at": "2026-09-25T12:12:44",
    },
    {
        "id": 11,
        "text": "വ്യാഴത്തിലെ ഗ്രേറ്റ് റെഡ് സ്പോട്ട് എന്ന കൊടുങ്കാറ്റിന് ഭൂമിയേക്കാൾ വലിപ്പമുണ്ട്.",
        "topic": "space",
        "footage": "jupiter planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 12,
        "text": "ബഹിരാകാശത്ത് എത്തുമ്പോൾ ബഹിരാകാശയാത്രികരുടെ ഉയരം അഞ്ച് സെന്റിമീറ്റർ വരെ കൂടാറുണ്ട്.",
        "topic": "space",
        "footage": "astronaut",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 13,
        "text": "സൂര്യനോട് ഏറ്റവും അടുത്തുള്ളത് ബുധനാണെങ്കിലും ഏറ്റവും ചൂടുള്ള ഗ്രഹം ശുക്രനാണ്. അവിടെ താപനില നാനൂറ്റി അറുപത് ഡിഗ്രി സെൽഷ്യസിന് മുകളിലാണ്.",
        "topic": "space",
        "footage": "planet space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 14,
        "text": "ഭൂമിയിലെ എല്ലാ കടൽത്തീരങ്ങളിലെയും മണൽത്തരികളേക്കാൾ കൂടുതൽ നക്ഷത്രങ്ങൾ പ്രപഞ്ചത്തിലുണ്ട്.",
        "topic": "space",
        "footage": "milky way night sky",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 15,
        "text": "ശനിയുടെ ഉപഗ്രഹമായ എൻസെലാഡസ് ബഹിരാകാശത്തേക്ക് വെള്ളം ചീറ്റുന്നുണ്ട്. അവിടെ ജീവൻ ഉണ്ടാകാമെന്ന് ശാസ്ത്രജ്ഞർ കരുതുന്നു.",
        "topic": "aliens",
        "footage": "geyser",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 16,
        "text": "രാത്രി ആകാശത്ത് നക്ഷത്രങ്ങളെ നോക്കുമ്പോൾ നിങ്ങൾ കാണുന്നത് അവയുടെ ഭൂതകാലമാണ്. ആ പ്രകാശം വർഷങ്ങൾക്ക് മുമ്പ് പുറപ്പെട്ടതാണ്.",
        "topic": "space",
        "footage": "milky way night sky",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 17,
        "text": "സൂര്യനുള്ളിൽ പത്തുലക്ഷത്തിലധികം ഭൂമികളെ ഉൾക്കൊള്ളിക്കാം.",
        "topic": "space",
        "footage": "sun space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 18,
        "text": "ചൊവ്വയിലെ ഒളിമ്പസ് മോൺസ് എന്ന അഗ്നിപർവ്വതത്തിന് എവറസ്റ്റിനേക്കാൾ ഏകദേശം രണ്ടര മടങ്ങ് ഉയരമുണ്ട്.",
        "topic": "space",
        "footage": "mars planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 19,
        "text": "ഒരു മിന്നലിന്റെ ചൂട് സൂര്യന്റെ ഉപരിതലത്തേക്കാൾ ഏകദേശം അഞ്ച് മടങ്ങ് കൂടുതലാണ്.",
        "topic": "earth",
        "footage": "lightning",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 20,
        "text": "രണ്ടര ദശലക്ഷം പ്രകാശവർഷം അകലെയുള്ള ആൻഡ്രോമിഡ ഗാലക്സിയെ ഇരുണ്ട രാത്രിയിൽ നഗ്നനേത്രങ്ങൾ കൊണ്ട് കാണാം.",
        "topic": "space",
        "footage": "galaxy space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 21,
        "text": "അന്താരാഷ്ട്ര ബഹിരാകാശ നിലയം ഓരോ തൊണ്ണൂറ് മിനിറ്റിലും ഭൂമിയെ ചുറ്റുന്നു. അതിനാൽ അവിടെയുള്ളവർ ഒരു ദിവസം പതിനാറ് സൂര്യോദയങ്ങൾ കാണുന്നു.",
        "topic": "space",
        "footage": "space station",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 22,
        "text": "ആയിരത്തി തൊള്ളായിരത്തി എഴുപത്തിയേഴിൽ ബഹിരാകാശത്ത് നിന്ന് ഒരു ശക്തമായ റേഡിയോ സിഗ്നൽ ലഭിച്ചു. വൗ സിഗ്നൽ എന്ന് അറിയപ്പെടുന്ന അതിന്റെ ഉറവിടം ഇന്നും ആർക്കും വിശദീകരിക്കാനായിട്ടില്ല.",
        "topic": "aliens",
        "footage": "radio telescope",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 23,
        "text": "തേൻ ഒരിക്കലും കേടാകില്ല. ആയിരക്കണക്കിന് വർഷം പഴക്കമുള്ള ഈജിപ്ഷ്യൻ കല്ലറകളിൽ നിന്ന് കഴിക്കാവുന്ന തേൻ കണ്ടെത്തിയിട്ടുണ്ട്.",
        "topic": "earth",
        "footage": "honey",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 24,
        "text": "നീലത്തിമിംഗലത്തിന്റെ ഹൃദയത്തിന് ഒരു ചെറിയ കാറിന്റെ വലിപ്പമുണ്ട്.",
        "topic": "animals",
        "footage": "whale",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 25,
        "text": "വേനൽക്കാലത്ത് ചൂടുകൊണ്ട് ഇരുമ്പ് വികസിക്കുന്നതിനാൽ ഈഫൽ ടവറിന്റെ ഉയരം പതിനഞ്ച് സെന്റിമീറ്റർ വരെ കൂടും.",
        "topic": "earth",
        "footage": "eiffel tower",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 26,
        "text": "ബഹിരാകാശം പൂർണ്ണമായും നിശബ്ദമാണ്. ശബ്ദം സഞ്ചരിക്കാൻ അവിടെ വായുവില്ല.",
        "topic": "space",
        "footage": "outer space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 27,
        "text": "സൂര്യനിൽ നിന്നുള്ള പ്രകാശം ഭൂമിയിലെത്താൻ ഏകദേശം എട്ട് മിനിറ്റ് എടുക്കും. അതായത് നമ്മൾ കാണുന്നത് എട്ട് മിനിറ്റ് മുമ്പുള്ള സൂര്യനെയാണ്.",
        "topic": "space",
        "footage": "sun space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 28,
        "text": "നമ്മുടെ ക്ഷീരപഥ ഗാലക്സിയിൽ പതിനായിരം കോടിയിലധികം നക്ഷത്രങ്ങളുണ്ട്.",
        "topic": "space",
        "footage": "milky way galaxy",
        "status": "posted",
        "posted_at": "2026-09-25T09:51:44",
    },
    {
        "id": 29,
        "text": "നമുക്ക് നിരീക്ഷിക്കാൻ കഴിയുന്ന പ്രപഞ്ചത്തിന് ഒൻപതിനായിരം കോടിയിലധികം പ്രകാശവർഷം വ്യാസമുണ്ട്.",
        "topic": "space",
        "footage": "universe space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 30,
        "text": "ശുക്രനിലെ ഒരു ദിവസം, അവിടുത്തെ ഒരു വർഷത്തേക്കാൾ നീളമുള്ളതാണ്.",
        "topic": "space",
        "footage": "planet space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 31,
        "text": "മനുഷ്യന്റെ കണ്ണിന് ഏകദേശം ഒരു കോടി നിറങ്ങൾ തിരിച്ചറിയാൻ കഴിയും.",
        "topic": "body",
        "footage": "human eye",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 32,
        "text": "നീരാളിക്ക് മൂന്ന് ഹൃദയങ്ങളും നീല നിറമുള്ള രക്തവുമുണ്ട്.",
        "topic": "animals",
        "footage": "octopus",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 33,
        "text": "വാഴപ്പഴത്തിൽ ചെറിയ അളവിൽ റേഡിയോ ആക്ടീവ് പൊട്ടാസ്യം ഉണ്ട്. പക്ഷേ അത് ഒട്ടും അപകടകരമല്ല.",
        "topic": "earth",
        "footage": "banana",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 34,
        "text": "ടാർഡിഗ്രേഡ് എന്ന സൂക്ഷ്മജീവിക്ക് ബഹിരാകാശത്തിലെ ശൂന്യതയിൽ പോലും ജീവിച്ചിരിക്കാൻ കഴിയും.",
        "topic": "aliens",
        "footage": "microscope",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 35,
        "text": "നെപ്ട്യൂണിലെ ഒരു വർഷം ഭൂമിയിലെ ഏകദേശം നൂറ്റിയറുപത്തിയഞ്ച് വർഷങ്ങൾക്ക് തുല്യമാണ്.",
        "topic": "space",
        "footage": "planet space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 36,
        "text": "ചന്ദ്രനിൽ കാറ്റില്ലാത്തതിനാൽ, അവിടെ പതിഞ്ഞ ബഹിരാകാശയാത്രികരുടെ കാൽപ്പാടുകൾ ദശലക്ഷക്കണക്കിന് വർഷങ്ങൾ മായാതെ നിൽക്കും.",
        "topic": "space",
        "footage": "moon surface",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 37,
        "text": "കേരളത്തിലെ കുട്ടനാട്, സമുദ്രനിരപ്പിന് താഴെ കൃഷി ചെയ്യുന്ന ലോകത്തിലെ വളരെ കുറച്ച് സ്ഥലങ്ങളിൽ ഒന്നാണ്.",
        "topic": "earth",
        "footage": "kerala backwaters",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 38,
        "text": "ഭൂമിയിൽ മരങ്ങൾ ഉണ്ടാകുന്നതിനും മുമ്പേ സ്രാവുകൾ ഉണ്ടായിരുന്നു.",
        "topic": "animals",
        "footage": "shark",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 39,
        "text": "പ്രപഞ്ചത്തിൽ ഇരുപതിനായിരം കോടിയിലധികം ഗാലക്സികൾ ഉണ്ടെന്നാണ് ശാസ്ത്രജ്ഞരുടെ കണക്ക്.",
        "topic": "space",
        "footage": "galaxy space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 40,
        "text": "ശനി ഗ്രഹത്തിന്റെ സാന്ദ്രത വെള്ളത്തേക്കാൾ കുറവാണ്. അത്ര വലിയൊരു കടലുണ്ടെങ്കിൽ ശനി അതിൽ പൊങ്ങിക്കിടക്കും.",
        "topic": "space",
        "footage": "planet space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 41,
        "text": "നമ്മുടെ സൂര്യൻ ക്ഷീരപഥത്തിന്റെ കേന്ദ്രത്തെ ഒരു തവണ ചുറ്റാൻ ഏകദേശം ഇരുപത്തിമൂന്ന് കോടി വർഷമെടുക്കും.",
        "topic": "space",
        "footage": "milky way galaxy",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 42,
        "text": "ക്ഷീരപഥത്തിന് ഏകദേശം ഒരു ലക്ഷം പ്രകാശവർഷം വീതിയുണ്ട്.",
        "topic": "space",
        "footage": "milky way galaxy",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 43,
        "text": "പ്രകാശം ഒരു സെക്കൻഡിൽ ഏകദേശം മൂന്ന് ലക്ഷം കിലോമീറ്റർ സഞ്ചരിക്കും.",
        "topic": "space",
        "footage": "light rays space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 44,
        "text": "ഒരു പ്രകാശവർഷം എന്നത് സമയമല്ല, ദൂരമാണ്. പ്രകാശം ഒരു വർഷം കൊണ്ട് സഞ്ചരിക്കുന്ന ദൂരം.",
        "topic": "space",
        "footage": "stars space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 45,
        "text": "ക്ഷീരപഥവും ആൻഡ്രോമിഡയും ഭാവിയിൽ കൂട്ടിയിടിച്ച് ഒന്നായി മാറിയേക്കാം എന്നാണ് ശാസ്ത്രജ്ഞർ കരുതുന്നത്.",
        "topic": "space",
        "footage": "galaxy space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 46,
        "text": "സൂര്യനോട് ഏറ്റവും അടുത്തുള്ള നക്ഷത്രമായ പ്രോക്സിമ സെന്റോറി ഏകദേശം നാലേകാൽ പ്രകാശവർഷം അകലെയാണ്.",
        "topic": "space",
        "footage": "stars space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 47,
        "text": "ഗാലക്സികൾ കൂട്ടമായിട്ടാണ് കാണപ്പെടുന്നത്. നമ്മുടെ ക്ഷീരപഥം ലോക്കൽ ഗ്രൂപ്പ് എന്ന ഗാലക്സി കൂട്ടത്തിന്റെ ഭാഗമാണ്.",
        "topic": "space",
        "footage": "galaxy space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 48,
        "text": "ജെയിംസ് വെബ് ടെലിസ്കോപ്പ് പ്രപഞ്ചത്തിന്റെ തുടക്കകാലത്ത് രൂപംകൊണ്ട ഗാലക്സികളുടെ ചിത്രങ്ങൾ പകർത്തിയിട്ടുണ്ട്.",
        "topic": "space",
        "footage": "telescope space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 49,
        "text": "പ്രപഞ്ചത്തിന് ഏകദേശം ആയിരത്തി മുന്നൂറ്റി എൺപത് കോടി വർഷം പ്രായമുണ്ട്.",
        "topic": "space",
        "footage": "universe space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 50,
        "text": "പ്രപഞ്ചം ഇപ്പോഴും വികസിച്ചുകൊണ്ടിരിക്കുകയാണ്. ദൂരെയുള്ള ഗാലക്സികൾ നമ്മിൽ നിന്ന് അകന്നുപോവുകയാണ്.",
        "topic": "space",
        "footage": "galaxy space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 51,
        "text": "ഒരു തമോഗർത്തത്തിന്റെ ആകർഷണ ബലം വളരെ ശക്തമായതിനാൽ പ്രകാശത്തിന് പോലും അതിൽ നിന്ന് രക്ഷപ്പെടാനാവില്ല.",
        "topic": "space",
        "footage": "black hole space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 52,
        "text": "രണ്ടായിരത്തി പത്തൊൻപതിലാണ് മനുഷ്യൻ ആദ്യമായി ഒരു തമോഗർത്തത്തിന്റെ ചിത്രം പകർത്തിയത്.",
        "topic": "space",
        "footage": "black hole space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 53,
        "text": "സൂര്യൻ ഒരു ഇടത്തരം നക്ഷത്രം മാത്രമാണ്. സൂര്യനേക്കാൾ ആയിരം മടങ്ങിലധികം വലിപ്പമുള്ള നക്ഷത്രങ്ങൾ പ്രപഞ്ചത്തിലുണ്ട്.",
        "topic": "space",
        "footage": "stars space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 54,
        "text": "രാത്രിയിൽ നമ്മൾ നഗ്നനേത്രങ്ങൾ കൊണ്ട് കാണുന്ന നക്ഷത്രങ്ങളെല്ലാം നമ്മുടെ ക്ഷീരപഥ ഗാലക്സിയിലുള്ളവയാണ്.",
        "topic": "space",
        "footage": "milky way night sky",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 55,
        "text": "ബഹിരാകാശത്തിലെ പൊടിയും വാതകവും ചേർന്ന ഭീമൻ മേഘങ്ങളാണ് നെബുലകൾ. പുതിയ നക്ഷത്രങ്ങൾ ജനിക്കുന്നത് അവിടെയാണ്.",
        "topic": "space",
        "footage": "nebula space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 56,
        "text": "നമ്മുടെ ശരീരത്തിലെ പല മൂലകങ്ങളും കോടിക്കണക്കിന് വർഷങ്ങൾക്ക് മുമ്പ് നക്ഷത്രങ്ങൾക്കുള്ളിൽ രൂപംകൊണ്ടവയാണ്. നമ്മൾ നക്ഷത്രപ്പൊടിയാൽ നിർമ്മിതരാണ്.",
        "topic": "space",
        "footage": "stars space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 57,
        "text": "ക്ഷീരപഥം ഒരു സർപ്പിളാകൃതിയിലുള്ള ഗാലക്സിയാണ്. നമ്മുടെ സൗരയൂഥം അതിന്റെ ഒരു കൈയിലാണ്.",
        "topic": "space",
        "footage": "spiral galaxy",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 58,
        "text": "ചന്ദ്രൻ ഓരോ വർഷവും ഏകദേശം നാല് സെന്റിമീറ്റർ വീതം ഭൂമിയിൽ നിന്ന് അകന്നുപോകുന്നു.",
        "topic": "space",
        "footage": "moon surface",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 59,
        "text": "ശുക്രൻ മറ്റ് മിക്ക ഗ്രഹങ്ങളിൽ നിന്നും വ്യത്യസ്തമായി എതിർദിശയിലാണ് കറങ്ങുന്നത്. അവിടെ സൂര്യൻ പടിഞ്ഞാറ് ഉദിക്കും.",
        "topic": "space",
        "footage": "planet space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 60,
        "text": "വ്യാഴത്തിന് തൊണ്ണൂറിലധികം ഉപഗ്രഹങ്ങളുണ്ട്.",
        "topic": "space",
        "footage": "jupiter planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 61,
        "text": "ശനിയുടെ വലയങ്ങൾ പ്രധാനമായും മഞ്ഞുകട്ടകളും പാറക്കഷ്ണങ്ങളും കൊണ്ടാണ് നിർമ്മിച്ചിരിക്കുന്നത്.",
        "topic": "space",
        "footage": "saturn planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 62,
        "text": "ബഹിരാകാശത്ത് രണ്ട് ലോഹക്കഷ്ണങ്ങൾ തൊട്ടാൽ അവ തമ്മിൽ ഒട്ടിപ്പിടിക്കും. ഇതിനെ കോൾഡ് വെൽഡിംഗ് എന്ന് പറയുന്നു.",
        "topic": "space",
        "footage": "outer space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 63,
        "text": "ചൊവ്വയിലെ സൂര്യാസ്തമയം നീല നിറത്തിലാണ് കാണപ്പെടുന്നത്.",
        "topic": "space",
        "footage": "mars planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 64,
        "text": "ഒരു ഗാലക്സിയിൽ നിന്നുള്ള പ്രകാശം നമ്മളിലെത്താൻ ദശലക്ഷക്കണക്കിന് വർഷങ്ങൾ എടുക്കുന്നു. അതുകൊണ്ട് നമ്മൾ കാണുന്നത് ആ ഗാലക്സിയുടെ പഴയ രൂപമാണ്.",
        "topic": "space",
        "footage": "galaxy space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 65,
        "text": "സൂര്യന്റെ ഉള്ളിലെ താപനില ഏകദേശം ഒന്നരക്കോടി ഡിഗ്രി സെൽഷ്യസാണ്.",
        "topic": "space",
        "footage": "sun space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 66,
        "text": "ചൊവ്വയിൽ ഒരുകാലത്ത് നദികളും തടാകങ്ങളും ഉണ്ടായിരുന്നു എന്നതിന് തെളിവുകൾ ലഭിച്ചിട്ടുണ്ട്.",
        "topic": "aliens",
        "footage": "mars planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 67,
        "text": "ശനിയുടെ ഉപഗ്രഹമായ ടൈറ്റനിൽ മീഥെയ്ൻ കൊണ്ടുള്ള തടാകങ്ങളും മഴയുമുണ്ട്.",
        "topic": "aliens",
        "footage": "planet space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 68,
        "text": "നമ്മുടെ ഗാലക്സിയിൽ മാത്രം, ജീവൻ നിലനിൽക്കാൻ സാധ്യതയുള്ള മേഖലയിൽ കോടിക്കണക്കിന് ഗ്രഹങ്ങൾ ഉണ്ടാകാമെന്നാണ് ശാസ്ത്രജ്ഞരുടെ കണക്ക്.",
        "topic": "aliens",
        "footage": "planet space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 69,
        "text": "പ്രപഞ്ചത്തിൽ ഇത്രയധികം ഗ്രഹങ്ങളുണ്ടായിട്ടും അന്യഗ്രഹജീവികളെ കാണാത്തത് എന്തുകൊണ്ട് എന്ന ചോദ്യത്തെ ഫെർമി വിരോധാഭാസം എന്ന് വിളിക്കുന്നു.",
        "topic": "aliens",
        "footage": "galaxy space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 70,
        "text": "ഭൂമിയിൽ നിന്ന് അയച്ച റേഡിയോ സിഗ്നലുകൾ ഇപ്പോൾ നൂറിലധികം പ്രകാശവർഷം അകലെ വരെ എത്തിയിട്ടുണ്ട്.",
        "topic": "aliens",
        "footage": "radio telescope",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 71,
        "text": "ഭൂമിയിലെ ചില സൂക്ഷ്മജീവികൾക്ക് തിളച്ച വെള്ളത്തിലും കൊടും തണുപ്പിലും ജീവിക്കാൻ കഴിയും. അതുകൊണ്ട് മറ്റ് ഗ്രഹങ്ങളിലും ജീവൻ ഉണ്ടാകാമെന്ന് ശാസ്ത്രജ്ഞർ കരുതുന്നു.",
        "topic": "aliens",
        "footage": "microscope",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 72,
        "text": "ട്രാപ്പിസ്റ്റ് വൺ എന്ന നക്ഷത്രത്തിന് ചുറ്റും ഭൂമിയുടെ വലിപ്പമുള്ള ഏഴ് ഗ്രഹങ്ങളുണ്ട്.",
        "topic": "aliens",
        "footage": "planet space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 73,
        "text": "ബഹിരാകാശത്ത് നിന്ന് ഭൂമിയിൽ പതിച്ച ചില ഉൽക്കകളിൽ ജീവന്റെ അടിസ്ഥാന ഘടകങ്ങളായ അമിനോ ആസിഡുകൾ കണ്ടെത്തിയിട്ടുണ്ട്.",
        "topic": "aliens",
        "footage": "meteor",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 74,
        "text": "നീരാളിയുടെ നാഡീകോശങ്ങളിൽ മൂന്നിൽ രണ്ട് ഭാഗവും അതിന്റെ കൈകളിലാണ്.",
        "topic": "animals",
        "footage": "octopus",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 75,
        "text": "ഒട്ടകപ്പക്ഷിയുടെ കണ്ണ് അതിന്റെ തലച്ചോറിനേക്കാൾ വലുതാണ്.",
        "topic": "animals",
        "footage": "ostrich",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 76,
        "text": "തേനീച്ചകൾ നൃത്തത്തിലൂടെയാണ് പൂക്കൾ എവിടെയാണെന്ന് മറ്റുള്ളവയ്ക്ക് പറഞ്ഞുകൊടുക്കുന്നത്.",
        "topic": "animals",
        "footage": "bees flowers",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 77,
        "text": "ആനകൾക്ക് കാലുകളിലൂടെ ഭൂമിയിലെ കമ്പനങ്ങൾ തിരിച്ചറിയാൻ കഴിയും.",
        "topic": "animals",
        "footage": "elephant",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 78,
        "text": "മനുഷ്യശരീരത്തിലെ രക്തക്കുഴലുകൾ നീളത്തിൽ നിരത്തിയാൽ ഭൂമിയെ രണ്ട് തവണയിലധികം ചുറ്റാൻ കഴിയും.",
        "topic": "body",
        "footage": "human body",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 79,
        "text": "ഒരു മനുഷ്യൻ ജീവിതകാലത്ത് ശരാശരി ആറ് വർഷത്തോളം സ്വപ്നം കാണുന്നു.",
        "topic": "body",
        "footage": "sleeping",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 80,
        "text": "കുഞ്ഞുങ്ങൾ ജനിക്കുമ്പോൾ ഏകദേശം മുന്നൂറ് എല്ലുകളുണ്ട്. വളരുമ്പോൾ ചിലത് ചേർന്ന് ഇരുനൂറ്റി ആറ് ആകുന്നു.",
        "topic": "body",
        "footage": "newborn baby",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 81,
        "text": "എവറസ്റ്റ് കൊടുമുടി ഓരോ വർഷവും ഏതാനും മില്ലിമീറ്റർ വീതം ഉയരം കൂടിക്കൊണ്ടിരിക്കുന്നു.",
        "topic": "earth",
        "footage": "mountain snow",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 82,
        "text": "ഭൂമിയിലെ ഓക്സിജന്റെ വലിയൊരു ഭാഗം ഉത്പാദിപ്പിക്കുന്നത് കടലിലെ സൂക്ഷ്മസസ്യങ്ങളാണ്.",
        "topic": "earth",
        "footage": "ocean",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 83,
        "text": "ഭൂമിയിലെ സമുദ്രങ്ങളുടെ വലിയൊരു ഭാഗം ഇപ്പോഴും മനുഷ്യൻ പര്യവേക്ഷണം ചെയ്തിട്ടില്ല.",
        "topic": "earth",
        "footage": "deep ocean",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 84,
        "text": "കേരളത്തിലെ പശ്ചിമഘട്ടം ലോകത്തിലെ ജൈവവൈവിധ്യ ഹോട്ട്സ്പോട്ടുകളിൽ ഒന്നാണ്.",
        "topic": "earth",
        "footage": "western ghats",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 85,
        "text": "നീലക്കുറിഞ്ഞി പന്ത്രണ്ട് വർഷത്തിൽ ഒരിക്കൽ മാത്രമാണ് പൂക്കുന്നത്.",
        "topic": "earth",
        "footage": "purple flowers mountain",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 86,
        "text": "ഹമ്മിങ്ബേർഡ് എന്ന കുഞ്ഞുപക്ഷിക്ക് പിന്നോട്ടും പറക്കാൻ കഴിയും.",
        "topic": "animals",
        "footage": "hummingbird",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 87,
        "text": "കടൽനീർനായകൾ ഉറങ്ങുമ്പോൾ ഒഴുകിപ്പോകാതിരിക്കാൻ പരസ്പരം കൈ പിടിച്ചാണ് ഉറങ്ങുന്നത്.",
        "topic": "animals",
        "footage": "sea otter",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 88,
        "text": "കാക്കകൾക്ക് മനുഷ്യരുടെ മുഖം ഓർത്തുവയ്ക്കാൻ കഴിയും. ഉപദ്രവിച്ചവരെ അവ വർഷങ്ങളോളം ഓർക്കും.",
        "topic": "animals",
        "footage": "crow bird",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 89,
        "text": "ഫ്ലമിംഗോ പക്ഷികൾക്ക് പിങ്ക് നിറം കിട്ടുന്നത് അവ കഴിക്കുന്ന ചെറുജീവികളിൽ നിന്നും പായലിൽ നിന്നുമാണ്.",
        "topic": "animals",
        "footage": "flamingo",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 90,
        "text": "ജിറാഫിന്റെ നാക്കിന് ഏകദേശം അര മീറ്റർ നീളമുണ്ട്.",
        "topic": "animals",
        "footage": "giraffe",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 91,
        "text": "കോലകളുടെ വിരലടയാളം മനുഷ്യരുടേതിനോട് വളരെ സാമ്യമുള്ളതാണ്.",
        "topic": "animals",
        "footage": "koala",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 92,
        "text": "ചീറ്റയ്ക്ക് ഏകദേശം മൂന്ന് സെക്കൻഡിനുള്ളിൽ മണിക്കൂറിൽ നൂറ് കിലോമീറ്റർ വേഗതയിലെത്താൻ കഴിയും.",
        "topic": "animals",
        "footage": "cheetah running",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 93,
        "text": "മൂങ്ങകൾക്ക് കണ്ണുകൾ ചലിപ്പിക്കാനാവില്ല. അതുകൊണ്ടാണ് അവ തല ഏകദേശം ഇരുനൂറ്റിയെഴുപത് ഡിഗ്രി വരെ തിരിക്കുന്നത്.",
        "topic": "animals",
        "footage": "owl",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 94,
        "text": "ഡോൾഫിനുകൾ ഉറങ്ങുമ്പോൾ തലച്ചോറിന്റെ ഒരു പകുതി മാത്രമേ ഉറങ്ങുകയുള്ളൂ.",
        "topic": "animals",
        "footage": "dolphins",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 95,
        "text": "ചിത്രശലഭങ്ങൾ കാലുകൾ കൊണ്ടാണ് രുചി അറിയുന്നത്.",
        "topic": "animals",
        "footage": "butterfly",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 96,
        "text": "ഇത്ര വലിയ ശരീരമുണ്ടായിട്ടും ആനകൾക്ക് ചാടാൻ കഴിയില്ല.",
        "topic": "animals",
        "footage": "elephant",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 97,
        "text": "നക്ഷത്രമത്സ്യത്തിന് തലച്ചോറോ രക്തമോ ഇല്ല.",
        "topic": "animals",
        "footage": "starfish",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 98,
        "text": "മുട്ടയിടാൻ കൂട് ഉണ്ടാക്കുന്ന ലോകത്തിലെ ഏക പാമ്പാണ് രാജവെമ്പാല.",
        "topic": "animals",
        "footage": "king cobra",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 99,
        "text": "ഉറുമ്പുകൾക്ക് സ്വന്തം ശരീരഭാരത്തിന്റെ പല മടങ്ങ് ഭാരം ചുമക്കാൻ കഴിയും.",
        "topic": "animals",
        "footage": "ants",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 100,
        "text": "ചെമ്മീനിന്റെ ഹൃദയം അതിന്റെ തലയിലാണ്.",
        "topic": "animals",
        "footage": "shrimp underwater",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 101,
        "text": "ആമാശയത്തിന്റെ ഉൾപ്പാളി ഏതാനും ദിവസം കൂടുമ്പോൾ പുതുക്കപ്പെടുന്നു. ഇല്ലെങ്കിൽ ആമാശയത്തിലെ ആസിഡ് അതിനെത്തന്നെ ദഹിപ്പിക്കും.",
        "topic": "body",
        "footage": "human body",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 102,
        "text": "തുടയെല്ലാണ് നമ്മുടെ ശരീരത്തിലെ ഏറ്റവും നീളവും ബലവുമുള്ള എല്ല്.",
        "topic": "body",
        "footage": "human skeleton",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 103,
        "text": "നമ്മുടെ ശരീരത്തിലെ ഏറ്റവും ചെറിയ എല്ല് ചെവിക്കുള്ളിലാണ്.",
        "topic": "body",
        "footage": "ear closeup",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 104,
        "text": "നമ്മുടെ ഹൃദയം ഒരു ദിവസം ഏകദേശം ഒരു ലക്ഷം തവണ മിടിക്കുന്നു.",
        "topic": "body",
        "footage": "heartbeat",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 105,
        "text": "നിങ്ങൾക്ക് സ്വയം ഇക്കിളിയാക്കാൻ കഴിയില്ല. നമ്മുടെ ചലനങ്ങൾ തലച്ചോർ മുൻകൂട്ടി അറിയുന്നതാണ് കാരണം.",
        "topic": "body",
        "footage": "people laughing",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 106,
        "text": "ഒരേപോലെയിരിക്കുന്ന ഇരട്ടകൾക്ക് പോലും വിരലടയാളം വ്യത്യസ്തമാണ്.",
        "topic": "body",
        "footage": "fingerprint",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 107,
        "text": "രാവിലെ നമുക്ക് രാത്രിയേക്കാൾ ഏകദേശം ഒരു സെന്റിമീറ്റർ ഉയരം കൂടുതലായിരിക്കും.",
        "topic": "body",
        "footage": "morning stretch",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 108,
        "text": "നമ്മൾ ഒരു മിനിറ്റിൽ ഏകദേശം പതിനഞ്ച് മുതൽ ഇരുപത് തവണ വരെ കണ്ണ് ചിമ്മുന്നു.",
        "topic": "body",
        "footage": "human eye closeup",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 109,
        "text": "തലച്ചോറിന് സ്വയം വേദന അനുഭവപ്പെടില്ല. വേദന തിരിച്ചറിയുന്ന നാഡികൾ തലച്ചോറിനുള്ളിലില്ല.",
        "topic": "body",
        "footage": "brain",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 110,
        "text": "ചർമ്മമാണ് നമ്മുടെ ശരീരത്തിലെ ഏറ്റവും വലിയ അവയവം.",
        "topic": "body",
        "footage": "skin closeup",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 111,
        "text": "കരളിന്റെ ഒരു ഭാഗം മുറിച്ചുമാറ്റിയാലും അത് വീണ്ടും വളർന്നുവരും.",
        "topic": "body",
        "footage": "doctor hospital",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 112,
        "text": "പല്ലിന്റെ ഇനാമലാണ് നമ്മുടെ ശരീരത്തിലെ ഏറ്റവും കടുപ്പമുള്ള വസ്തു.",
        "topic": "body",
        "footage": "smile teeth",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 113,
        "text": "ലോകത്തിലെ ഏറ്റവും വലിയ മരുഭൂമി സഹാറയല്ല, അന്റാർട്ടിക്കയാണ്.",
        "topic": "earth",
        "footage": "antarctica ice",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 114,
        "text": "പസഫിക് സമുദ്രം ഭൂമിയിലെ എല്ലാ കരഭാഗങ്ങളും ചേർന്നതിനേക്കാൾ വലുതാണ്.",
        "topic": "earth",
        "footage": "pacific ocean",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 115,
        "text": "റഷ്യയ്ക്ക് പതിനൊന്ന് സമയമേഖലകളുണ്ട്.",
        "topic": "earth",
        "footage": "russia landscape",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 116,
        "text": "മേഘാലയയിലെ മൗസിൻറാം ആണ് ലോകത്ത് ഏറ്റവും കൂടുതൽ മഴ ലഭിക്കുന്ന സ്ഥലങ്ങളിൽ ഒന്ന്.",
        "topic": "earth",
        "footage": "heavy rain",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 117,
        "text": "ഇന്ത്യയിൽ ആദ്യമായി മൺസൂൺ മഴ എത്തുന്നത് കേരളത്തിലാണ്.",
        "topic": "earth",
        "footage": "monsoon rain",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 118,
        "text": "ഭൂമിയിൽ ഓരോ സെക്കൻഡിലും ഏകദേശം നൂറ് തവണ മിന്നൽ പതിക്കുന്നു.",
        "topic": "earth",
        "footage": "lightning storm",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 119,
        "text": "ചാവുകടലിൽ ഉപ്പ് വളരെ കൂടുതലായതിനാൽ അവിടെ ആരും മുങ്ങിപ്പോകില്ല, വെള്ളത്തിൽ പൊങ്ങിക്കിടക്കും.",
        "topic": "earth",
        "footage": "dead sea floating",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 120,
        "text": "ചുവട്ടിൽ നിന്ന് അളന്നാൽ ഏറ്റവും ഉയരമുള്ള പർവ്വതം എവറസ്റ്റല്ല. കടലിനടിയിൽ നിന്ന് തുടങ്ങുന്ന ഹവായിയിലെ മൗന കിയ ആണ്.",
        "topic": "earth",
        "footage": "hawaii volcano",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 121,
        "text": "ലോകത്തിലെ ഏറ്റവും വലിയ നദികളിൽ ഒന്നായ ആമസോണിന് കുറുകെ ഒരു പാലം പോലുമില്ല.",
        "topic": "earth",
        "footage": "amazon river",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 122,
        "text": "ഏതാനും ആയിരം വർഷങ്ങൾക്ക് മുമ്പ് സഹാറ മരുഭൂമി പുൽമേടുകളും തടാകങ്ങളും നിറഞ്ഞ പച്ചപ്പുള്ള പ്രദേശമായിരുന്നു.",
        "topic": "earth",
        "footage": "sahara desert",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 123,
        "text": "ഭൂമിയിലെ ചില മരങ്ങൾക്ക് നാലായിരത്തിലധികം വർഷം പ്രായമുണ്ട്.",
        "topic": "earth",
        "footage": "ancient trees",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 124,
        "text": "ചിലയിനം മുളകൾ ഒരു ദിവസം തൊണ്ണൂറ് സെന്റിമീറ്റർ വരെ വളരും.",
        "topic": "earth",
        "footage": "bamboo forest",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 125,
        "text": "ഭൂമിയിൽ രേഖപ്പെടുത്തിയ ഏറ്റവും കുറഞ്ഞ താപനില മൈനസ് എൺപത്തിയൊൻപത് ഡിഗ്രി സെൽഷ്യസാണ്, അന്റാർട്ടിക്കയിൽ.",
        "topic": "earth",
        "footage": "snow blizzard",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 126,
        "text": "ആയിരത്തി തൊള്ളായിരത്തി തൊണ്ണൂറ്റി ഒന്നിൽ ഇന്ത്യയിലെ ആദ്യത്തെ സമ്പൂർണ്ണ സാക്ഷരതാ സംസ്ഥാനമായി കേരളം പ്രഖ്യാപിക്കപ്പെട്ടു.",
        "topic": "kerala",
        "footage": "kerala village",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 127,
        "text": "ലോകത്തിലെ ആദ്യത്തെ പൂർണ്ണമായും സൗരോർജ്ജത്തിൽ പ്രവർത്തിക്കുന്ന വിമാനത്താവളം നമ്മുടെ കൊച്ചി വിമാനത്താവളമാണ്.",
        "topic": "kerala",
        "footage": "solar panels",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 128,
        "text": "കൊച്ചിയിലെ പരദേശി സിനഗോഗ്, കോമൺവെൽത്ത് രാജ്യങ്ങളിൽ ഇപ്പോഴും പ്രവർത്തിക്കുന്ന ഏറ്റവും പഴയ ജൂത ആരാധനാലയമാണ്.",
        "topic": "kerala",
        "footage": "fort kochi",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 129,
        "text": "കൊടുങ്ങല്ലൂരിലെ ചേരമാൻ ജുമാ മസ്ജിദ് ഇന്ത്യയിലെ ഏറ്റവും പഴയ മസ്ജിദായി കണക്കാക്കപ്പെടുന്നു.",
        "topic": "kerala",
        "footage": "old mosque",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 130,
        "text": "ആയിരത്തി നാനൂറ്റി തൊണ്ണൂറ്റിയെട്ടിൽ വാസ്കോഡ ഗാമ കപ്പലിറങ്ങിയത് കോഴിക്കോടിനടുത്തുള്ള കാപ്പാട് ആണ്.",
        "topic": "kerala",
        "footage": "old ship sea",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 131,
        "text": "ഇന്ത്യയിലേക്ക് കടൽമാർഗം കണ്ടെത്തിയ വാസ്കോഡ ഗാമ മരിച്ചത് കൊച്ചിയിൽ വെച്ചാണ്.",
        "topic": "kerala",
        "footage": "fort kochi",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 132,
        "text": "കഥകളി കലാകാരന്മാർക്ക് മുഖത്തെഴുത്തിന് മാത്രം മണിക്കൂറുകൾ വേണ്ടിവരും.",
        "topic": "kerala",
        "footage": "kathakali",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 133,
        "text": "ലോകത്തിലെ ഏറ്റവും പഴക്കമുള്ള ആയോധന കലകളിൽ ഒന്നാണ് നമ്മുടെ കളരിപ്പയറ്റ്.",
        "topic": "kerala",
        "footage": "martial arts training",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 134,
        "text": "കറുത്ത പൊന്ന് എന്നറിയപ്പെട്ടിരുന്ന കേരളത്തിലെ കുരുമുളക് വാങ്ങാൻ രണ്ടായിരം വർഷം മുമ്പ് റോമിൽ നിന്നുപോലും കച്ചവടക്കാർ എത്തിയിരുന്നു.",
        "topic": "kerala",
        "footage": "black pepper spice",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 135,
        "text": "ചെറിയൊരു സംസ്ഥാനമായിട്ടും കേരളത്തിൽ നാൽപ്പത്തിനാല് നദികളുണ്ട്.",
        "topic": "kerala",
        "footage": "kerala river",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 136,
        "text": "പെരിയാറാണ് കേരളത്തിലെ ഏറ്റവും നീളം കൂടിയ നദി.",
        "topic": "kerala",
        "footage": "river forest",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 137,
        "text": "വള്ളംകളിയിലെ ഒരു ചുണ്ടൻ വള്ളത്തിൽ നൂറിലധികം തുഴച്ചിൽക്കാർ ഉണ്ടാകാം.",
        "topic": "kerala",
        "footage": "boat race",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 138,
        "text": "ദക്ഷിണേന്ത്യയിലെ ഏറ്റവും ഉയരം കൂടിയ കൊടുമുടിയായ ആനമുടി കേരളത്തിലാണ്.",
        "topic": "kerala",
        "footage": "misty mountains",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 139,
        "text": "ഇന്ത്യയിൽ പുരുഷന്മാരേക്കാൾ കൂടുതൽ സ്ത്രീകളുള്ള സംസ്ഥാനമാണ് കേരളം.",
        "topic": "kerala",
        "footage": "kerala people",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 140,
        "text": "നമ്മുടെ തലച്ചോറിന് ഒരേ സമയം രണ്ട് കാര്യങ്ങളിൽ പൂർണ്ണ ശ്രദ്ധ കൊടുക്കാൻ കഴിയില്ല. അത് വേഗത്തിൽ മാറിമാറി ശ്രദ്ധിക്കുകയാണ് ചെയ്യുന്നത്.",
        "topic": "mind",
        "footage": "busy person",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 141,
        "text": "പൂർത്തിയാക്കാത്ത ജോലികൾ, പൂർത്തിയാക്കിയവയേക്കാൾ നന്നായി നമ്മൾ ഓർത്തിരിക്കും.",
        "topic": "mind",
        "footage": "writing notes",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 142,
        "text": "ഒരാൾ കോട്ടുവായിടുന്നത് കണ്ടാൽ നമുക്കും കോട്ടുവായിടാൻ തോന്നും. ഇതിനെക്കുറിച്ച് വായിക്കുമ്പോൾ പോലും.",
        "topic": "mind",
        "footage": "person yawning",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 143,
        "text": "ഉണർന്ന് കുറച്ച് മിനിറ്റുകൾക്കുള്ളിൽ, കണ്ട സ്വപ്നത്തിന്റെ വലിയൊരു ഭാഗവും നമ്മൾ മറന്നുപോകും.",
        "topic": "mind",
        "footage": "sleeping person",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 144,
        "text": "ഫോൺ വൈബ്രേറ്റ് ചെയ്യാതെ തന്നെ വൈബ്രേറ്റ് ചെയ്തതായി പലർക്കും തോന്നാറുണ്ട്. ഇതിനെ ഫാന്റം വൈബ്രേഷൻ എന്ന് പറയുന്നു.",
        "topic": "mind",
        "footage": "smartphone",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 145,
        "text": "ഒരു മുറിയിലേക്ക് കയറുമ്പോൾ എന്തിനാണ് വന്നതെന്ന് മറന്നുപോകാറുണ്ടോ? വാതിൽ കടക്കുന്നത് തന്നെ ഇതിന് കാരണമാകാമെന്ന് പഠനങ്ങൾ പറയുന്നു.",
        "topic": "mind",
        "footage": "open door room",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 146,
        "text": "എത്ര ബഹളമുള്ള സ്ഥലത്തും ആരെങ്കിലും നിങ്ങളുടെ പേര് വിളിച്ചാൽ നിങ്ങൾ അത് ഉടൻ കേൾക്കും.",
        "topic": "mind",
        "footage": "crowd party",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 147,
        "text": "മേഘങ്ങളിലും ചുമരിലും മുഖങ്ങൾ കാണുന്നത് തലച്ചോറിന്റെ ഒരു സ്വഭാവമാണ്. ഇതിനെ പാരിഡോളിയ എന്ന് പറയുന്നു.",
        "topic": "mind",
        "footage": "clouds sky",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 148,
        "text": "ഒരു പാട്ടിന്റെ ഒരു ഭാഗം മാത്രം മനസ്സിൽ വീണ്ടും വീണ്ടും വരുന്നതിനെ ഇയർവേം എന്ന് പറയുന്നു.",
        "topic": "mind",
        "footage": "headphones music",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 149,
        "text": "ഈ നിമിഷം മുമ്പ് നടന്നതുപോലെ തോന്നുന്ന ദേജാ വൂ അനുഭവം മിക്ക ആളുകൾക്കും ഉണ്ടാകാറുണ്ട്.",
        "topic": "mind",
        "footage": "person thinking",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 150,
        "text": "ഓരോ തവണ ഒരു ഓർമ്മ ഓർത്തെടുക്കുമ്പോഴും നമ്മുടെ തലച്ചോർ അതിനെ ചെറുതായി മാറ്റിയെഴുതുന്നുണ്ട്.",
        "topic": "mind",
        "footage": "old photographs",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 151,
        "text": "ഒരു രാത്രി മുഴുവൻ ഉറങ്ങാതിരുന്നാൽ തലച്ചോറിന്റെ പ്രവർത്തനം മദ്യപിച്ച ഒരാളുടേതിന് സമാനമാകുമെന്ന് പഠനങ്ങൾ പറയുന്നു.",
        "topic": "mind",
        "footage": "tired person night",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 152,
        "text": "ആദ്യകാലത്ത് ക്യാരറ്റുകൾ പ്രധാനമായും പർപ്പിൾ നിറത്തിലായിരുന്നു.",
        "topic": "food",
        "footage": "carrots",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 153,
        "text": "കശുവണ്ടി കശുമാങ്ങയുടെ പുറത്താണ് വളരുന്നത്. പോർച്ചുഗീസുകാരാണ് കശുമാവിനെ ഇന്ത്യയിൽ കൊണ്ടുവന്നത്.",
        "topic": "food",
        "footage": "cashew",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 154,
        "text": "നമ്മുടെ കറികളിലെ മുളക് ഇന്ത്യക്കാരനല്ല. ഏകദേശം അഞ്ഞൂറ് വർഷം മുമ്പ് പോർച്ചുഗീസുകാരാണ് അമേരിക്കയിൽ നിന്ന് അത് ഇവിടെ എത്തിച്ചത്.",
        "topic": "food",
        "footage": "red chilli",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 155,
        "text": "കേരളത്തിന്റെ പ്രിയപ്പെട്ട കപ്പ തെക്കേ അമേരിക്കയിൽ നിന്ന് വന്നതാണ്. ക്ഷാമകാലത്ത് തിരുവിതാംകൂറിലാണ് ഇത് ജനകീയമായത്.",
        "topic": "food",
        "footage": "cassava",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 156,
        "text": "സ്ട്രോബെറി ശാസ്ത്രീയമായി ഒരു ബെറിയല്ല. എന്നാൽ വാഴപ്പഴം ഒരു ബെറിയാണ്.",
        "topic": "food",
        "footage": "strawberries",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 157,
        "text": "ഒരുകാലത്ത് യൂറോപ്പിൽ തക്കാളി വിഷമാണെന്ന് ആളുകൾ വിശ്വസിച്ചിരുന്നു.",
        "topic": "food",
        "footage": "tomatoes",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 158,
        "text": "ഏലം സുഗന്ധവ്യഞ്ജനങ്ങളുടെ റാണി എന്നാണ് അറിയപ്പെടുന്നത്. കുരുമുളകാണ് രാജാവ്.",
        "topic": "food",
        "footage": "cardamom spice",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 159,
        "text": "ആപ്പിളിന്റെ ഏകദേശം നാലിലൊന്ന് ഭാഗം വായുവാണ്. അതുകൊണ്ട് അത് വെള്ളത്തിൽ പൊങ്ങിക്കിടക്കും.",
        "topic": "food",
        "footage": "apples water",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 160,
        "text": "നിലക്കടല ശരിക്കും ഒരു നട്ട് അല്ല, പയറുവർഗ്ഗത്തിൽ പെട്ടതാണ്.",
        "topic": "food",
        "footage": "peanuts",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 161,
        "text": "നമുക്ക് പ്രിയപ്പെട്ട ചോക്ലേറ്റ് നായ്ക്കൾക്ക് വിഷമാണ്.",
        "topic": "food",
        "footage": "dog",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 162,
        "text": "വെള്ളം കഴിഞ്ഞാൽ ലോകത്ത് ഏറ്റവും കൂടുതൽ കുടിക്കുന്ന പാനീയം ചായയാണ്.",
        "topic": "food",
        "footage": "tea cup",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 163,
        "text": "തെങ്ങ് കേരളത്തിന്റെ കല്പവൃക്ഷമാണ്. തേങ്ങ മുതൽ ഓല വരെ അതിന്റെ എല്ലാ ഭാഗവും മനുഷ്യൻ ഉപയോഗിക്കുന്നു.",
        "topic": "food",
        "footage": "coconut",
        "status": "pending",
        "posted_at": None,
    },
]
