"""
facts_ml.py
─────────────────────────────────────────────────────────────
Central store for all Malayalam facts used by the YouTube Shorts bot.

Each entry is a dict with these fields:
  {
    "id"        : unique int  (never reuse / reorder),
    "text"      : the fact in Malayalam (spoken + shown as captions),
    "topic"     : "space" | "aliens" | "animals" | "body" | "earth"
                  (picks the on-screen label and fallback footage),
    "footage"   : English Pexels search term for this fact's background video,
    "status"    : "pending" | "posted"   ← updated by quote_status.py after upload
    "posted_at" : ISO-8601 UTC string, or None
  }

quote_status.py reads and writes the "status" / "posted_at" fields
directly in this file so everything stays in one place — no separate JSON needed.

To add a new fact: append a new dict with a unique id,
status="pending", and posted_at=None.
Facts are never re-posted: once every fact is posted the bot stops
with an error until new facts are added here.
─────────────────────────────────────────────────────────────
"""

DEFAULT_QUOTES = [
    {
        "id": 1,
        "text": "നമ്മുടെ സൗരയൂഥത്തിന് പുറത്ത് അയ്യായിരത്തിലധികം ഗ്രഹങ്ങളെ ശാസ്ത്രജ്ഞർ ഇതിനകം കണ്ടെത്തിയിട്ടുണ്ട്.",
        "topic": "aliens",
        "footage": "planet space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 2,
        "text": "വ്യാഴത്തിന്റെ ഉപഗ്രഹമായ യൂറോപ്പയിലെ മഞ്ഞുപാളിക്കടിയിൽ, ഭൂമിയിലെ എല്ലാ സമുദ്രങ്ങളിലും ഉള്ളതിനേക്കാൾ കൂടുതൽ വെള്ളമുള്ള ഒരു കടൽ ഒളിഞ്ഞിരിപ്പുണ്ട്.",
        "topic": "aliens",
        "footage": "europa moon",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 3,
        "text": "നിങ്ങളുടെ ശരീരത്തിൽ ഏകദേശം മുപ്പത്തിയേഴ് ലക്ഷം കോടി കോശങ്ങളുണ്ട്.",
        "topic": "body",
        "footage": "human body",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 4,
        "text": "നിങ്ങളുടെ തലച്ചോർ ശരീരഭാരത്തിന്റെ രണ്ട് ശതമാനം മാത്രമാണെങ്കിലും ശരീരത്തിന്റെ ഊർജ്ജത്തിന്റെ ഇരുപത് ശതമാനം ഉപയോഗിക്കുന്നു.",
        "topic": "body",
        "footage": "brain",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 5,
        "text": "ആയിരത്തി തൊള്ളായിരത്തി എഴുപത്തിനാലിൽ മനുഷ്യൻ അന്യഗ്രഹജീവികൾക്കായി ഒരു റേഡിയോ സന്ദേശം അയച്ചു. അത് ലക്ഷ്യസ്ഥാനത്ത് എത്താൻ ഇരുപത്തയ്യായിരം വർഷമെടുക്കും.",
        "topic": "aliens",
        "footage": "radio telescope",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 6,
        "text": "ഭൂമിയുടെ ഭ്രമണവേഗം പതിയെ കുറയുന്നു. അതുകൊണ്ട് ദിവസങ്ങളുടെ നീളം വളരെ ചെറിയ അളവിൽ കൂടിക്കൊണ്ടിരിക്കുന്നു.",
        "topic": "earth",
        "footage": "earth from space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 7,
        "text": "ആൻഡ്രോമിഡ ഗാലക്സി സെക്കൻഡിൽ ഏകദേശം നൂറ്റിപ്പത്ത് കിലോമീറ്റർ വേഗത്തിൽ നമ്മുടെ ഗാലക്സിയുടെ നേരെ നീങ്ങിക്കൊണ്ടിരിക്കുകയാണ്.",
        "topic": "space",
        "footage": "galaxy space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 8,
        "text": "വോയേജർ പേടകത്തിൽ, അന്യഗ്രഹജീവികൾക്കായി ഭൂമിയിലെ ശബ്ദങ്ങളും അമ്പത്തിയഞ്ച് ഭാഷകളിലെ ആശംസകളും അടങ്ങിയ ഒരു സ്വർണ്ണ റെക്കോർഡുണ്ട്.",
        "topic": "aliens",
        "footage": "spacecraft space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 9,
        "text": "നമ്മുടെ ഗാലക്സിയുടെ നടുവിൽ, സൂര്യനേക്കാൾ നാല്പത് ലക്ഷം മടങ്ങ് പിണ്ഡമുള്ള ഒരു ഭീമൻ തമോഗർത്തമുണ്ട്.",
        "topic": "space",
        "footage": "black hole space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 10,
        "text": "ഒരു ന്യൂട്രോൺ നക്ഷത്രത്തിൽ നിന്ന് ഒരു സ്പൂൺ പദാർത്ഥം എടുത്താൽ, അതിന് ഏകദേശം നൂറുകോടി ടൺ ഭാരമുണ്ടാകും.",
        "topic": "space",
        "footage": "stars space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 11,
        "text": "വ്യാഴത്തിലെ ഗ്രേറ്റ് റെഡ് സ്പോട്ട് എന്ന കൊടുങ്കാറ്റിന് ഭൂമിയേക്കാൾ വലിപ്പമുണ്ട്.",
        "topic": "space",
        "footage": "jupiter planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 12,
        "text": "ബഹിരാകാശത്ത് എത്തുമ്പോൾ ബഹിരാകാശയാത്രികരുടെ ഉയരം അഞ്ച് സെന്റിമീറ്റർ വരെ കൂടാറുണ്ട്.",
        "topic": "space",
        "footage": "astronaut",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 13,
        "text": "സൂര്യനോട് ഏറ്റവും അടുത്തുള്ളത് ബുധനാണെങ്കിലും ഏറ്റവും ചൂടുള്ള ഗ്രഹം ശുക്രനാണ്. അവിടെ താപനില നാനൂറ്റി അറുപത് ഡിഗ്രി സെൽഷ്യസിന് മുകളിലാണ്.",
        "topic": "space",
        "footage": "planet space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 14,
        "text": "ഭൂമിയിലെ എല്ലാ കടൽത്തീരങ്ങളിലെയും മണൽത്തരികളേക്കാൾ കൂടുതൽ നക്ഷത്രങ്ങൾ പ്രപഞ്ചത്തിലുണ്ട്.",
        "topic": "space",
        "footage": "milky way night sky",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 15,
        "text": "ശനിയുടെ ഉപഗ്രഹമായ എൻസെലാഡസ് ബഹിരാകാശത്തേക്ക് വെള്ളം ചീറ്റുന്നുണ്ട്. അവിടെ ജീവൻ ഉണ്ടാകാമെന്ന് ശാസ്ത്രജ്ഞർ കരുതുന്നു.",
        "topic": "aliens",
        "footage": "geyser",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 16,
        "text": "രാത്രി ആകാശത്ത് നക്ഷത്രങ്ങളെ നോക്കുമ്പോൾ നിങ്ങൾ കാണുന്നത് അവയുടെ ഭൂതകാലമാണ്. ആ പ്രകാശം വർഷങ്ങൾക്ക് മുമ്പ് പുറപ്പെട്ടതാണ്.",
        "topic": "space",
        "footage": "milky way night sky",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 17,
        "text": "സൂര്യനുള്ളിൽ പത്തുലക്ഷത്തിലധികം ഭൂമികളെ ഉൾക്കൊള്ളിക്കാം.",
        "topic": "space",
        "footage": "sun space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 18,
        "text": "ചൊവ്വയിലെ ഒളിമ്പസ് മോൺസ് എന്ന അഗ്നിപർവ്വതത്തിന് എവറസ്റ്റിനേക്കാൾ ഏകദേശം രണ്ടര മടങ്ങ് ഉയരമുണ്ട്.",
        "topic": "space",
        "footage": "mars planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 19,
        "text": "ഒരു മിന്നലിന്റെ ചൂട് സൂര്യന്റെ ഉപരിതലത്തേക്കാൾ ഏകദേശം അഞ്ച് മടങ്ങ് കൂടുതലാണ്.",
        "topic": "earth",
        "footage": "lightning",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 20,
        "text": "രണ്ടര ദശലക്ഷം പ്രകാശവർഷം അകലെയുള്ള ആൻഡ്രോമിഡ ഗാലക്സിയെ ഇരുണ്ട രാത്രിയിൽ നഗ്നനേത്രങ്ങൾ കൊണ്ട് കാണാം.",
        "topic": "space",
        "footage": "galaxy space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 21,
        "text": "അന്താരാഷ്ട്ര ബഹിരാകാശ നിലയം ഓരോ തൊണ്ണൂറ് മിനിറ്റിലും ഭൂമിയെ ചുറ്റുന്നു. അതിനാൽ അവിടെയുള്ളവർ ഒരു ദിവസം പതിനാറ് സൂര്യോദയങ്ങൾ കാണുന്നു.",
        "topic": "space",
        "footage": "space station",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 22,
        "text": "ആയിരത്തി തൊള്ളായിരത്തി എഴുപത്തിയേഴിൽ ബഹിരാകാശത്ത് നിന്ന് ഒരു ശക്തമായ റേഡിയോ സിഗ്നൽ ലഭിച്ചു. വൗ സിഗ്നൽ എന്ന് അറിയപ്പെടുന്ന അതിന്റെ ഉറവിടം ഇന്നും ആർക്കും വിശദീകരിക്കാനായിട്ടില്ല.",
        "topic": "aliens",
        "footage": "radio telescope",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 23,
        "text": "തേൻ ഒരിക്കലും കേടാകില്ല. ആയിരക്കണക്കിന് വർഷം പഴക്കമുള്ള ഈജിപ്ഷ്യൻ കല്ലറകളിൽ നിന്ന് കഴിക്കാവുന്ന തേൻ കണ്ടെത്തിയിട്ടുണ്ട്.",
        "topic": "earth",
        "footage": "honey",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 24,
        "text": "നീലത്തിമിംഗലത്തിന്റെ ഹൃദയത്തിന് ഒരു ചെറിയ കാറിന്റെ വലിപ്പമുണ്ട്.",
        "topic": "animals",
        "footage": "whale",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 25,
        "text": "വേനൽക്കാലത്ത് ചൂടുകൊണ്ട് ഇരുമ്പ് വികസിക്കുന്നതിനാൽ ഈഫൽ ടവറിന്റെ ഉയരം പതിനഞ്ച് സെന്റിമീറ്റർ വരെ കൂടും.",
        "topic": "earth",
        "footage": "eiffel tower",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 26,
        "text": "ബഹിരാകാശം പൂർണ്ണമായും നിശബ്ദമാണ്. ശബ്ദം സഞ്ചരിക്കാൻ അവിടെ വായുവില്ല.",
        "topic": "space",
        "footage": "outer space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 27,
        "text": "സൂര്യനിൽ നിന്നുള്ള പ്രകാശം ഭൂമിയിലെത്താൻ ഏകദേശം എട്ട് മിനിറ്റ് എടുക്കും. അതായത് നമ്മൾ കാണുന്നത് എട്ട് മിനിറ്റ് മുമ്പുള്ള സൂര്യനെയാണ്.",
        "topic": "space",
        "footage": "sun space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 28,
        "text": "നമ്മുടെ ക്ഷീരപഥ ഗാലക്സിയിൽ പതിനായിരം കോടിയിലധികം നക്ഷത്രങ്ങളുണ്ട്.",
        "topic": "space",
        "footage": "milky way galaxy",
        "status": "posted",
        "posted_at": "2026-09-25T09:51:44",
    },
    {
        "id": 29,
        "text": "നമുക്ക് നിരീക്ഷിക്കാൻ കഴിയുന്ന പ്രപഞ്ചത്തിന് ഒൻപതിനായിരം കോടിയിലധികം പ്രകാശവർഷം വ്യാസമുണ്ട്.",
        "topic": "space",
        "footage": "universe space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 30,
        "text": "ശുക്രനിലെ ഒരു ദിവസം, അവിടുത്തെ ഒരു വർഷത്തേക്കാൾ നീളമുള്ളതാണ്.",
        "topic": "space",
        "footage": "planet space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 31,
        "text": "മനുഷ്യന്റെ കണ്ണിന് ഏകദേശം ഒരു കോടി നിറങ്ങൾ തിരിച്ചറിയാൻ കഴിയും.",
        "topic": "body",
        "footage": "human eye",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 32,
        "text": "നീരാളിക്ക് മൂന്ന് ഹൃദയങ്ങളും നീല നിറമുള്ള രക്തവുമുണ്ട്.",
        "topic": "animals",
        "footage": "octopus",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 33,
        "text": "വാഴപ്പഴത്തിൽ ചെറിയ അളവിൽ റേഡിയോ ആക്ടീവ് പൊട്ടാസ്യം ഉണ്ട്. പക്ഷേ അത് ഒട്ടും അപകടകരമല്ല.",
        "topic": "earth",
        "footage": "banana",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 34,
        "text": "ടാർഡിഗ്രേഡ് എന്ന സൂക്ഷ്മജീവിക്ക് ബഹിരാകാശത്തിലെ ശൂന്യതയിൽ പോലും ജീവിച്ചിരിക്കാൻ കഴിയും.",
        "topic": "aliens",
        "footage": "microscope",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 35,
        "text": "നെപ്ട്യൂണിലെ ഒരു വർഷം ഭൂമിയിലെ ഏകദേശം നൂറ്റിയറുപത്തിയഞ്ച് വർഷങ്ങൾക്ക് തുല്യമാണ്.",
        "topic": "space",
        "footage": "planet space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 36,
        "text": "ചന്ദ്രനിൽ കാറ്റില്ലാത്തതിനാൽ, അവിടെ പതിഞ്ഞ ബഹിരാകാശയാത്രികരുടെ കാൽപ്പാടുകൾ ദശലക്ഷക്കണക്കിന് വർഷങ്ങൾ മായാതെ നിൽക്കും.",
        "topic": "space",
        "footage": "moon surface",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 37,
        "text": "കേരളത്തിലെ കുട്ടനാട്, സമുദ്രനിരപ്പിന് താഴെ കൃഷി ചെയ്യുന്ന ലോകത്തിലെ വളരെ കുറച്ച് സ്ഥലങ്ങളിൽ ഒന്നാണ്.",
        "topic": "earth",
        "footage": "kerala backwaters",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 38,
        "text": "ഭൂമിയിൽ മരങ്ങൾ ഉണ്ടാകുന്നതിനും മുമ്പേ സ്രാവുകൾ ഉണ്ടായിരുന്നു.",
        "topic": "animals",
        "footage": "shark",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 39,
        "text": "പ്രപഞ്ചത്തിൽ ഇരുപതിനായിരം കോടിയിലധികം ഗാലക്സികൾ ഉണ്ടെന്നാണ് ശാസ്ത്രജ്ഞരുടെ കണക്ക്.",
        "topic": "space",
        "footage": "galaxy space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 40,
        "text": "ശനി ഗ്രഹത്തിന്റെ സാന്ദ്രത വെള്ളത്തേക്കാൾ കുറവാണ്. അത്ര വലിയൊരു കടലുണ്ടെങ്കിൽ ശനി അതിൽ പൊങ്ങിക്കിടക്കും.",
        "topic": "space",
        "footage": "planet space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 41,
        "text": "നമ്മുടെ സൂര്യൻ ക്ഷീരപഥത്തിന്റെ കേന്ദ്രത്തെ ഒരു തവണ ചുറ്റാൻ ഏകദേശം ഇരുപത്തിമൂന്ന് കോടി വർഷമെടുക്കും.",
        "topic": "space",
        "footage": "milky way galaxy",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 42,
        "text": "ക്ഷീരപഥത്തിന് ഏകദേശം ഒരു ലക്ഷം പ്രകാശവർഷം വീതിയുണ്ട്.",
        "topic": "space",
        "footage": "milky way galaxy",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 43,
        "text": "പ്രകാശം ഒരു സെക്കൻഡിൽ ഏകദേശം മൂന്ന് ലക്ഷം കിലോമീറ്റർ സഞ്ചരിക്കും.",
        "topic": "space",
        "footage": "light rays space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 44,
        "text": "ഒരു പ്രകാശവർഷം എന്നത് സമയമല്ല, ദൂരമാണ്. പ്രകാശം ഒരു വർഷം കൊണ്ട് സഞ്ചരിക്കുന്ന ദൂരം.",
        "topic": "space",
        "footage": "stars space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 45,
        "text": "ക്ഷീരപഥവും ആൻഡ്രോമിഡയും ഭാവിയിൽ കൂട്ടിയിടിച്ച് ഒന്നായി മാറിയേക്കാം എന്നാണ് ശാസ്ത്രജ്ഞർ കരുതുന്നത്.",
        "topic": "space",
        "footage": "galaxy space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 46,
        "text": "സൂര്യനോട് ഏറ്റവും അടുത്തുള്ള നക്ഷത്രമായ പ്രോക്സിമ സെന്റോറി ഏകദേശം നാലേകാൽ പ്രകാശവർഷം അകലെയാണ്.",
        "topic": "space",
        "footage": "stars space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 47,
        "text": "ഗാലക്സികൾ കൂട്ടമായിട്ടാണ് കാണപ്പെടുന്നത്. നമ്മുടെ ക്ഷീരപഥം ലോക്കൽ ഗ്രൂപ്പ് എന്ന ഗാലക്സി കൂട്ടത്തിന്റെ ഭാഗമാണ്.",
        "topic": "space",
        "footage": "galaxy space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 48,
        "text": "ജെയിംസ് വെബ് ടെലിസ്കോപ്പ് പ്രപഞ്ചത്തിന്റെ തുടക്കകാലത്ത് രൂപംകൊണ്ട ഗാലക്സികളുടെ ചിത്രങ്ങൾ പകർത്തിയിട്ടുണ്ട്.",
        "topic": "space",
        "footage": "telescope space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 49,
        "text": "പ്രപഞ്ചത്തിന് ഏകദേശം ആയിരത്തി മുന്നൂറ്റി എൺപത് കോടി വർഷം പ്രായമുണ്ട്.",
        "topic": "space",
        "footage": "universe space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 50,
        "text": "പ്രപഞ്ചം ഇപ്പോഴും വികസിച്ചുകൊണ്ടിരിക്കുകയാണ്. ദൂരെയുള്ള ഗാലക്സികൾ നമ്മിൽ നിന്ന് അകന്നുപോവുകയാണ്.",
        "topic": "space",
        "footage": "galaxy space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 51,
        "text": "ഒരു തമോഗർത്തത്തിന്റെ ആകർഷണ ബലം വളരെ ശക്തമായതിനാൽ പ്രകാശത്തിന് പോലും അതിൽ നിന്ന് രക്ഷപ്പെടാനാവില്ല.",
        "topic": "space",
        "footage": "black hole space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 52,
        "text": "രണ്ടായിരത്തി പത്തൊൻപതിലാണ് മനുഷ്യൻ ആദ്യമായി ഒരു തമോഗർത്തത്തിന്റെ ചിത്രം പകർത്തിയത്.",
        "topic": "space",
        "footage": "black hole space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 53,
        "text": "സൂര്യൻ ഒരു ഇടത്തരം നക്ഷത്രം മാത്രമാണ്. സൂര്യനേക്കാൾ ആയിരം മടങ്ങിലധികം വലിപ്പമുള്ള നക്ഷത്രങ്ങൾ പ്രപഞ്ചത്തിലുണ്ട്.",
        "topic": "space",
        "footage": "stars space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 54,
        "text": "രാത്രിയിൽ നമ്മൾ നഗ്നനേത്രങ്ങൾ കൊണ്ട് കാണുന്ന നക്ഷത്രങ്ങളെല്ലാം നമ്മുടെ ക്ഷീരപഥ ഗാലക്സിയിലുള്ളവയാണ്.",
        "topic": "space",
        "footage": "milky way night sky",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 55,
        "text": "ബഹിരാകാശത്തിലെ പൊടിയും വാതകവും ചേർന്ന ഭീമൻ മേഘങ്ങളാണ് നെബുലകൾ. പുതിയ നക്ഷത്രങ്ങൾ ജനിക്കുന്നത് അവിടെയാണ്.",
        "topic": "space",
        "footage": "nebula space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 56,
        "text": "നമ്മുടെ ശരീരത്തിലെ പല മൂലകങ്ങളും കോടിക്കണക്കിന് വർഷങ്ങൾക്ക് മുമ്പ് നക്ഷത്രങ്ങൾക്കുള്ളിൽ രൂപംകൊണ്ടവയാണ്. നമ്മൾ നക്ഷത്രപ്പൊടിയാൽ നിർമ്മിതരാണ്.",
        "topic": "space",
        "footage": "stars space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 57,
        "text": "ക്ഷീരപഥം ഒരു സർപ്പിളാകൃതിയിലുള്ള ഗാലക്സിയാണ്. നമ്മുടെ സൗരയൂഥം അതിന്റെ ഒരു കൈയിലാണ്.",
        "topic": "space",
        "footage": "spiral galaxy",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 58,
        "text": "ചന്ദ്രൻ ഓരോ വർഷവും ഏകദേശം നാല് സെന്റിമീറ്റർ വീതം ഭൂമിയിൽ നിന്ന് അകന്നുപോകുന്നു.",
        "topic": "space",
        "footage": "moon surface",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 59,
        "text": "ശുക്രൻ മറ്റ് മിക്ക ഗ്രഹങ്ങളിൽ നിന്നും വ്യത്യസ്തമായി എതിർദിശയിലാണ് കറങ്ങുന്നത്. അവിടെ സൂര്യൻ പടിഞ്ഞാറ് ഉദിക്കും.",
        "topic": "space",
        "footage": "planet space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 60,
        "text": "വ്യാഴത്തിന് തൊണ്ണൂറിലധികം ഉപഗ്രഹങ്ങളുണ്ട്.",
        "topic": "space",
        "footage": "jupiter planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 61,
        "text": "ശനിയുടെ വലയങ്ങൾ പ്രധാനമായും മഞ്ഞുകട്ടകളും പാറക്കഷ്ണങ്ങളും കൊണ്ടാണ് നിർമ്മിച്ചിരിക്കുന്നത്.",
        "topic": "space",
        "footage": "saturn planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 62,
        "text": "ബഹിരാകാശത്ത് രണ്ട് ലോഹക്കഷ്ണങ്ങൾ തൊട്ടാൽ അവ തമ്മിൽ ഒട്ടിപ്പിടിക്കും. ഇതിനെ കോൾഡ് വെൽഡിംഗ് എന്ന് പറയുന്നു.",
        "topic": "space",
        "footage": "outer space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 63,
        "text": "ചൊവ്വയിലെ സൂര്യാസ്തമയം നീല നിറത്തിലാണ് കാണപ്പെടുന്നത്.",
        "topic": "space",
        "footage": "mars planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 64,
        "text": "ഒരു ഗാലക്സിയിൽ നിന്നുള്ള പ്രകാശം നമ്മളിലെത്താൻ ദശലക്ഷക്കണക്കിന് വർഷങ്ങൾ എടുക്കുന്നു. അതുകൊണ്ട് നമ്മൾ കാണുന്നത് ആ ഗാലക്സിയുടെ പഴയ രൂപമാണ്.",
        "topic": "space",
        "footage": "galaxy space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 65,
        "text": "സൂര്യന്റെ ഉള്ളിലെ താപനില ഏകദേശം ഒന്നരക്കോടി ഡിഗ്രി സെൽഷ്യസാണ്.",
        "topic": "space",
        "footage": "sun space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 66,
        "text": "ചൊവ്വയിൽ ഒരുകാലത്ത് നദികളും തടാകങ്ങളും ഉണ്ടായിരുന്നു എന്നതിന് തെളിവുകൾ ലഭിച്ചിട്ടുണ്ട്.",
        "topic": "aliens",
        "footage": "mars planet",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 67,
        "text": "ശനിയുടെ ഉപഗ്രഹമായ ടൈറ്റനിൽ മീഥെയ്ൻ കൊണ്ടുള്ള തടാകങ്ങളും മഴയുമുണ്ട്.",
        "topic": "aliens",
        "footage": "planet space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 68,
        "text": "നമ്മുടെ ഗാലക്സിയിൽ മാത്രം, ജീവൻ നിലനിൽക്കാൻ സാധ്യതയുള്ള മേഖലയിൽ കോടിക്കണക്കിന് ഗ്രഹങ്ങൾ ഉണ്ടാകാമെന്നാണ് ശാസ്ത്രജ്ഞരുടെ കണക്ക്.",
        "topic": "aliens",
        "footage": "planet space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 69,
        "text": "പ്രപഞ്ചത്തിൽ ഇത്രയധികം ഗ്രഹങ്ങളുണ്ടായിട്ടും അന്യഗ്രഹജീവികളെ കാണാത്തത് എന്തുകൊണ്ട് എന്ന ചോദ്യത്തെ ഫെർമി വിരോധാഭാസം എന്ന് വിളിക്കുന്നു.",
        "topic": "aliens",
        "footage": "galaxy space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 70,
        "text": "ഭൂമിയിൽ നിന്ന് അയച്ച റേഡിയോ സിഗ്നലുകൾ ഇപ്പോൾ നൂറിലധികം പ്രകാശവർഷം അകലെ വരെ എത്തിയിട്ടുണ്ട്.",
        "topic": "aliens",
        "footage": "radio telescope",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 71,
        "text": "ഭൂമിയിലെ ചില സൂക്ഷ്മജീവികൾക്ക് തിളച്ച വെള്ളത്തിലും കൊടും തണുപ്പിലും ജീവിക്കാൻ കഴിയും. അതുകൊണ്ട് മറ്റ് ഗ്രഹങ്ങളിലും ജീവൻ ഉണ്ടാകാമെന്ന് ശാസ്ത്രജ്ഞർ കരുതുന്നു.",
        "topic": "aliens",
        "footage": "microscope",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 72,
        "text": "ട്രാപ്പിസ്റ്റ് വൺ എന്ന നക്ഷത്രത്തിന് ചുറ്റും ഭൂമിയുടെ വലിപ്പമുള്ള ഏഴ് ഗ്രഹങ്ങളുണ്ട്.",
        "topic": "aliens",
        "footage": "planet space",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 73,
        "text": "ബഹിരാകാശത്ത് നിന്ന് ഭൂമിയിൽ പതിച്ച ചില ഉൽക്കകളിൽ ജീവന്റെ അടിസ്ഥാന ഘടകങ്ങളായ അമിനോ ആസിഡുകൾ കണ്ടെത്തിയിട്ടുണ്ട്.",
        "topic": "aliens",
        "footage": "meteor",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 74,
        "text": "നീരാളിയുടെ നാഡീകോശങ്ങളിൽ മൂന്നിൽ രണ്ട് ഭാഗവും അതിന്റെ കൈകളിലാണ്.",
        "topic": "animals",
        "footage": "octopus",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 75,
        "text": "ഒട്ടകപ്പക്ഷിയുടെ കണ്ണ് അതിന്റെ തലച്ചോറിനേക്കാൾ വലുതാണ്.",
        "topic": "animals",
        "footage": "ostrich",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 76,
        "text": "തേനീച്ചകൾ നൃത്തത്തിലൂടെയാണ് പൂക്കൾ എവിടെയാണെന്ന് മറ്റുള്ളവയ്ക്ക് പറഞ്ഞുകൊടുക്കുന്നത്.",
        "topic": "animals",
        "footage": "bees flowers",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 77,
        "text": "ആനകൾക്ക് കാലുകളിലൂടെ ഭൂമിയിലെ കമ്പനങ്ങൾ തിരിച്ചറിയാൻ കഴിയും.",
        "topic": "animals",
        "footage": "elephant",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 78,
        "text": "മനുഷ്യശരീരത്തിലെ രക്തക്കുഴലുകൾ നീളത്തിൽ നിരത്തിയാൽ ഭൂമിയെ രണ്ട് തവണയിലധികം ചുറ്റാൻ കഴിയും.",
        "topic": "body",
        "footage": "human body",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 79,
        "text": "ഒരു മനുഷ്യൻ ജീവിതകാലത്ത് ശരാശരി ആറ് വർഷത്തോളം സ്വപ്നം കാണുന്നു.",
        "topic": "body",
        "footage": "sleeping",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 80,
        "text": "കുഞ്ഞുങ്ങൾ ജനിക്കുമ്പോൾ ഏകദേശം മുന്നൂറ് എല്ലുകളുണ്ട്. വളരുമ്പോൾ ചിലത് ചേർന്ന് ഇരുനൂറ്റി ആറ് ആകുന്നു.",
        "topic": "body",
        "footage": "newborn baby",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 81,
        "text": "എവറസ്റ്റ് കൊടുമുടി ഓരോ വർഷവും ഏതാനും മില്ലിമീറ്റർ വീതം ഉയരം കൂടിക്കൊണ്ടിരിക്കുന്നു.",
        "topic": "earth",
        "footage": "mountain snow",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 82,
        "text": "ഭൂമിയിലെ ഓക്സിജന്റെ വലിയൊരു ഭാഗം ഉത്പാദിപ്പിക്കുന്നത് കടലിലെ സൂക്ഷ്മസസ്യങ്ങളാണ്.",
        "topic": "earth",
        "footage": "ocean",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 83,
        "text": "ഭൂമിയിലെ സമുദ്രങ്ങളുടെ വലിയൊരു ഭാഗം ഇപ്പോഴും മനുഷ്യൻ പര്യവേക്ഷണം ചെയ്തിട്ടില്ല.",
        "topic": "earth",
        "footage": "deep ocean",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 84,
        "text": "കേരളത്തിലെ പശ്ചിമഘട്ടം ലോകത്തിലെ ജൈവവൈവിധ്യ ഹോട്ട്സ്പോട്ടുകളിൽ ഒന്നാണ്.",
        "topic": "earth",
        "footage": "western ghats",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 85,
        "text": "നീലക്കുറിഞ്ഞി പന്ത്രണ്ട് വർഷത്തിൽ ഒരിക്കൽ മാത്രമാണ് പൂക്കുന്നത്.",
        "topic": "earth",
        "footage": "purple flowers mountain",
        "status": "pending",
        "posted_at": None,
    },
]
