"""
quotes.py
─────────────────────────────────────────────────────────────
Central store for all English quotes used by the YouTube Shorts bot.

Each entry is a dict with these fields:
  {
    "id"        : unique int  (never reuse / reorder),
    "text"      : the quote string,
    "author"    : speaker name in English (used for footage, voice and hashtags),
    "status"    : "pending" | "posted"   ← updated by quote_status.py after upload
    "posted_at" : ISO-8601 UTC string, or None
  }

quote_status.py reads and writes the "status" / "posted_at" fields
directly in this file so everything stays in one place — no separate JSON needed.

To add a new quote: append a new dict with a unique id,
status="pending", and posted_at=None.
Quotes are never re-posted: once every quote is posted the bot stops
with an error until new quotes are added here.
─────────────────────────────────────────────────────────────
"""

DEFAULT_QUOTES = [
    {
        "id": 1,
        "text": "I think the reason why I am the person who I am today is because I went through those tough times when I was younger.",
        "author": "LeBron James",
        "status": "posted",
        "posted_at": "2026-09-22T08:08:30",
    },
    {
        "id": 2,
        "text": "Ask me to play. I'll play. Ask me to shoot. I'll shoot. Ask me to pass. I'll pass. Ask me to steal, block out, sacrifice, lead, dominate. Anything. But it's not what you ask of me. It's what I ask of myself.",
        "author": "LeBron James",
        "status": "posted",
        "posted_at": "2026-09-22T14:09:40",
    },
    {
        "id": 3,
        "text": "I always say, decisions I make, I live with them. There's always ways you can correct them or ways you can do them better. At the end of the day, I live with them.",
        "author": "LeBron James",
        "status": "posted",
        "posted_at": "2026-09-22T18:30:47",
    },
    {
        "id": 4,
        "text": "To be successful you have to be selfish, or else you never achieve. And once you get to your highest level, then you have to be unselfish. Stay reachable. Stay in touch. Don't isolate.",
        "author": "Michael Jordan",
        "status": "posted",
        "posted_at": "2026-09-22T23:30:52",
    },
    {
        "id": 5,
        "text": "The basketball court for me, during a game, is the most peaceful place I can imagine. On the basketball court, I worry about nothing. When I'm out there, no one can bother me.",
        "author": "Michael Jordan",
        "status": "posted",
        "posted_at": "2026-09-23T02:20:26",
    },
    {
        "id": 6,
        "text": "Obstacles don't have to stop you. If you run into a wall, don't turn around and give up. Figure out how to climb it, go through it, or work around it.",
        "author": "Michael Jordan",
        "status": "posted",
        "posted_at": "2026-09-23T08:12:01",
    },
    {
        "id": 7,
        "text": "Your love makes me strong, your hate makes me unstoppable.",
        "author": "Cristiano Ronaldo",
        "status": "posted",
        "posted_at": "2026-09-23T14:02:42",
    },
    {
        "id": 8,
        "text": "Talent without working hard is nothing. I'm not perfectionistic, but I like to feel that I have done my best.",
        "author": "Cristiano Ronaldo",
        "status": "posted",
        "posted_at": "2026-09-23T18:51:02",
    },
    {
        "id": 9,
        "text": "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing or learning to do.",
        "author": "Pele",
        "status": "posted",
        "posted_at": "2026-09-23T23:24:21",
    },
    {
        "id": 10,
        "text": "People throw stones at you and you convert them into milestones.",
        "author": "Sachin Tendulkar",
        "status": "posted",
        "posted_at": "2026-09-24T02:04:13",
    },
    {
        "id": 11,
        "text": "I'm a fighter. I believe in the eye-for-an-eye business. I'm no cheek turner. I got no respect for a man who won't hit back. You kill my dog, you better hide your cat.",
        "author": "Muhammad Ali",
        "status": "posted",
        "posted_at": "2026-09-24T08:00:47",
    },
    {
        "id": 12,
        "text": "Don't count the days, make the days count.",
        "author": "Muhammad Ali",
        "status": "posted",
        "posted_at": "2026-09-24T12:15:36",
    },
    {
        "id": 13,
        "text": "The most important thing is to try and inspire people so that they can be great in whatever they want to do.",
        "author": "Kobe Bryant",
        "status": "posted",
        "posted_at": "2026-09-24T13:58:24",
    },
    {
        "id": 14,
        "text": "Everything negative — pressure, challenges — is all an opportunity for me to rise.",
        "author": "Kobe Bryant",
        "status": "posted",
        "posted_at": "2026-09-24T18:49:39",
    },
    {
        "id": 15,
        "text": "I have nothing in common with lazy people who blame others for their lack of success.",
        "author": "Kobe Bryant",
        "status": "posted",
        "posted_at": "2026-09-24T23:44:26",
    },
    {
        "id": 16,
        "text": "I really think a champion is defined not by their wins but by how they can recover when they fall.",
        "author": "Serena Williams",
        "status": "posted",
        "posted_at": "2026-09-25T02:20:23",
    },
    {
        "id": 17,
        "text": "I've had to learn to fight all my life — got to learn to keep smiling. If you smile, things will work out.",
        "author": "Serena Williams",
        "status": "posted",
        "posted_at": "2026-09-25T08:24:11",
    },
    {
        "id": 18,
        "text": "You always want to win. That is why you play tennis, because you love the sport and you try to be the best you can at it.",
        "author": "Roger Federer",
        "status": "posted",
        "posted_at": "2026-09-25T14:24:05",
    },
    {
        "id": 19,
        "text": "I know what I can do, so I never doubt myself.",
        "author": "Usain Bolt",
        "status": "posted",
        "posted_at": "2026-09-20T17:51:19",
    },
    {
        "id": 20,
        "text": "Worrying gets you nowhere. If you turn up worrying about how you're going to perform, you've already lost. Train hard, turn up, run your best, and the rest will take care of itself.",
        "author": "Usain Bolt",
        "status": "posted",
        "posted_at": "2026-09-20T20:03:41",
    },
    {
        "id": 21,
        "text": "No matter how good you get you can always get better, and that's the exciting part.",
        "author": "Tiger Woods",
        "status": "posted",
        "posted_at": "2026-09-20T22:53:16",
    },
    {
        "id": 22,
        "text": "You miss one hundred percent of the shots you don't take.",
        "author": "Wayne Gretzky",
        "status": "posted",
        "posted_at": "2026-09-21T02:10:39",
    },
    {
        "id": 23,
        "text": "Failure happens all the time. It happens every day in practice. What makes you better is how you react to it.",
        "author": "Mia Hamm",
        "status": "posted",
        "posted_at": "2026-09-21T08:25:27",
    },
    {
        "id": 24,
        "text": "We all have dreams. But in order to make dreams come into reality, it takes an awful lot of determination, dedication, self-discipline, and effort.",
        "author": "Jesse Owens",
        "status": "posted",
        "posted_at": "2026-09-21T15:32:53",
    },
    {
        "id": 25,
        "text": "Champions keep playing until they get it right.",
        "author": "Billie Jean King",
        "status": "posted",
        "posted_at": "2026-09-21T21:24:41",
    },
    {
        "id": 26,
        "text": "Start where you are. Use what you have. Do what you can.",
        "author": "Arthur Ashe",
        "status": "posted",
        "posted_at": "2026-09-24T07:47:26",
    },
    {
        "id": 27,
        "text": "Failure is a part of success.",
        "author": "Hank Aaron",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 28,
        "text": "Self-belief and hard work will always earn you success.",
        "author": "Virat Kohli",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 29,
        "text": "There are better starters than me, but I'm a strong finisher.",
        "author": "Usain Bolt",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 30,
        "text": "Every strike brings me closer to the next home run.",
        "author": "Babe Ruth",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 31,
        "text": "The strength of the team is each individual member. The strength of each member is the team.",
        "author": "Phil Jackson",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 32,
        "text": "The last three or four reps is what makes the muscle grow.",
        "author": "Arnold Schwarzenegger",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 33,
        "text": "The success of every woman should be the inspiration to another. We should raise each other up.",
        "author": "Serena Williams",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 34,
        "text": "The day you think there is no improvements to be made is a sad one for any player.",
        "author": "Lionel Messi",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 35,
        "text": "Don't give up. Don't ever give up.",
        "author": "Jim Valvano",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 36,
        "text": "I can accept failure, everyone fails at something. But I can't accept not trying.",
        "author": "Michael Jordan",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 37,
        "text": "If everything seems under control, you're not going fast enough.",
        "author": "Mario Andretti",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 38,
        "text": "Rest at the end, not in the middle.",
        "author": "Kobe Bryant",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 39,
        "text": "There may be people that have more talent than you, but there's no excuse for anyone to work harder than you do.",
        "author": "Derek Jeter",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 40,
        "text": "Don't be afraid of failure. This is the way to succeed.",
        "author": "LeBron James",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 41,
        "text": "Always turn a negative situation into a positive situation.",
        "author": "Michael Jordan",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 42,
        "text": "If you think you're perfect already, then you never will be.",
        "author": "Cristiano Ronaldo",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 43,
        "text": "Once something is a passion, the motivation is there.",
        "author": "Michael Schumacher",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 44,
        "text": "It is better to look ahead and prepare than to look back and regret.",
        "author": "Jackie Joyner-Kersee",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 45,
        "text": "Ask not what your teammates can do for you. Ask what you can do for your teammates.",
        "author": "Magic Johnson",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 46,
        "text": "Strength does not come from winning. Your struggles develop your strengths. When you go through hardships and decide not to surrender, that is strength.",
        "author": "Arnold Schwarzenegger",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 47,
        "text": "Excellence is the gradual result of always striving to do better.",
        "author": "Pat Riley",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 48,
        "text": "I fear not the man who has practiced 10000 kicks once, but I fear the man who has practiced one kick 10000 times.",
        "author": "Bruce Lee",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 49,
        "text": "The battles that count aren't the ones for gold medals. The struggles within yourself, the invisible battles inside all of us, that's where it's at.",
        "author": "Jesse Owens",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 50,
        "text": "There's no failure in sports. There's good days, bad days. Some days you are able to be successful, some days you're not.",
        "author": "Giannis Antetokounmpo",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 51,
        "text": "A winner is someone who recognizes his God-given talents, works his tail off to develop them into skills, and uses these skills to accomplish his goals.",
        "author": "Larry Bird",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 52,
        "text": "It ain't over till it's over.",
        "author": "Yogi Berra",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 53,
        "text": "The moment you give up is the moment you let someone else win.",
        "author": "Kobe Bryant",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 54,
        "text": "It isn't the mountains ahead to climb that wear you out, it's the pebble in your shoe.",
        "author": "Muhammad Ali",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 55,
        "text": "If you no longer go for a gap that exists, you are no longer a racing driver.",
        "author": "Ayrton Senna",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 56,
        "text": "Winning takes care of everything.",
        "author": "Tiger Woods",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 57,
        "text": "Winning is great, sure, but if you are really going to do something in life, the secret is learning how to lose.",
        "author": "Wilma Rudolph",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 58,
        "text": "It's all about the journey, not the outcome.",
        "author": "Carl Lewis",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 59,
        "text": "Hard work has made it easy. That is my secret. That is why I win.",
        "author": "Nadia Comaneci",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 60,
        "text": "Dedication makes dreams come true.",
        "author": "Kobe Bryant",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 61,
        "text": "Be quick, but don't hurry.",
        "author": "John Wooden",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 62,
        "text": "Success is not an accident, success is actually a choice.",
        "author": "Stephen Curry",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 63,
        "text": "A good hockey player plays where the puck is. A great hockey player plays where the puck is going to be.",
        "author": "Wayne Gretzky",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 64,
        "text": "The more difficult the victory, the greater the happiness in winning.",
        "author": "Pele",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 65,
        "text": "You don't play for the crowd, you play for the country.",
        "author": "MS Dhoni",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 66,
        "text": "It's not whether you get knocked down, it's whether you get up.",
        "author": "Vince Lombardi",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 67,
        "text": "One man can be a crucial ingredient on a team, but one man cannot make a team.",
        "author": "Kareem Abdul-Jabbar",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 68,
        "text": "Do not pray for an easy life, pray for the strength to endure a difficult one.",
        "author": "Bruce Lee",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 69,
        "text": "You have to fight to reach your dream. You have to sacrifice and work hard for it.",
        "author": "Lionel Messi",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 70,
        "text": "Chase your dreams because dreams do come true.",
        "author": "Sachin Tendulkar",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 71,
        "text": "Luck has nothing to do with it, because I have spent many, many hours, countless hours, on the court working for my one moment in time, not knowing when it would come.",
        "author": "Serena Williams",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 72,
        "text": "It's not the load that breaks you down, it's the way you carry it.",
        "author": "Lou Holtz",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 73,
        "text": "To give anything less than your best is to sacrifice the gift.",
        "author": "Steve Prefontaine",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 74,
        "text": "Anything is possible!",
        "author": "Kevin Garnett",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 75,
        "text": "Discipline is doing what you hate to do, but doing it like you love it.",
        "author": "Mike Tyson",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 76,
        "text": "I'll do whatever it takes to win games, whether it's sitting on a bench waving a towel, handing a cup of water to a teammate, or hitting the game-winning shot.",
        "author": "Kobe Bryant",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 77,
        "text": "Don't let what you cannot do interfere with what you can do.",
        "author": "John Wooden",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 78,
        "text": "There's no talent here, this is hard work. This is an obsession.",
        "author": "Conor McGregor",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 79,
        "text": "I don't like to lose, at anything, yet I've grown most not from victories, but setbacks.",
        "author": "Serena Williams",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 80,
        "text": "A life is not important except in the impact it has on other lives.",
        "author": "Jackie Robinson",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 81,
        "text": "You can't put a limit on anything. The more you dream, the farther you get.",
        "author": "Michael Phelps",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 82,
        "text": "If you're afraid to fail, then you're probably going to fail.",
        "author": "Kobe Bryant",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 83,
        "text": "We don't want to tell our dreams. We want to show them.",
        "author": "Cristiano Ronaldo",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 84,
        "text": "Losing is not my enemy. Fear of losing is my enemy.",
        "author": "Rafael Nadal",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 85,
        "text": "I've always believed that if you put in the work, the results will come.",
        "author": "Michael Jordan",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 86,
        "text": "I am a member of a team, and I rely on the team, I defer to it and sacrifice for it, because the team, not the individual, is the ultimate champion.",
        "author": "Mia Hamm",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 87,
        "text": "Only the disciplined ones in life are free. If you are undisciplined, you are a slave to your moods and your passions.",
        "author": "Eliud Kipchoge",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 88,
        "text": "There is no way around hard work. Embrace it. You have to put in the hours because there's always something which you can improve.",
        "author": "Roger Federer",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 89,
        "text": "I fear no one, but respect everyone.",
        "author": "Roger Federer",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 90,
        "text": "The glory is being happy. The glory is not winning here or there. The glory is enjoying practicing, enjoying every day, enjoying to work hard, trying to be a better player than before.",
        "author": "Rafael Nadal",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 91,
        "text": "I'm not the next Usain Bolt or Michael Phelps. I'm the first Simone Biles.",
        "author": "Simone Biles",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 92,
        "text": "Never let the fear of striking out keep you from playing the game.",
        "author": "Babe Ruth",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 93,
        "text": "Being second is to be the first of the ones who lose.",
        "author": "Ayrton Senna",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 94,
        "text": "Everything is practice.",
        "author": "Pele",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 95,
        "text": "Good, better, best. Never let it rest. Until your good is better and your better is best.",
        "author": "Tim Duncan",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 96,
        "text": "Setting a goal is not the main thing. It is deciding how you will go about achieving it and staying with that plan.",
        "author": "Tom Landry",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 97,
        "text": "Talent wins games, but teamwork and intelligence win championships.",
        "author": "Michael Jordan",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 98,
        "text": "Never underestimate the power of dreams and the influence of the human spirit. The potential for greatness lives within each of us.",
        "author": "Wilma Rudolph",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 99,
        "text": "I like criticism. It makes you strong.",
        "author": "LeBron James",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 100,
        "text": "I think that everything is possible as long as you put your mind to it and you put the work and time into it.",
        "author": "Michael Phelps",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 101,
        "text": "Champions aren't made in gyms. Champions are made from something they have deep inside them, a desire, a dream, a vision.",
        "author": "Muhammad Ali",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 102,
        "text": "You have to be able to accept failure to get better.",
        "author": "LeBron James",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 103,
        "text": "I've missed more than 9000 shots in my career. I've lost almost 300 games. 26 times I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed.",
        "author": "Michael Jordan",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 104,
        "text": "Things turn out best for the people who make the best of the way things turn out.",
        "author": "John Wooden",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 105,
        "text": "Success isn't always about greatness. It's about consistency. Consistent hard work leads to success. Greatness will come.",
        "author": "Dwayne Johnson",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 106,
        "text": "Ability is what you're capable of doing. Motivation determines what you do. Attitude determines how well you do it.",
        "author": "Lou Holtz",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 107,
        "text": "The man who can drive himself further once the effort gets painful is the man who will win.",
        "author": "Roger Bannister",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 108,
        "text": "Pressure is a privilege.",
        "author": "Billie Jean King",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 109,
        "text": "Success is a journey, not a destination. The doing is often more important than the outcome.",
        "author": "Arthur Ashe",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 110,
        "text": "All kids need is a little help, a little hope, and somebody who believes in them.",
        "author": "Magic Johnson",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 111,
        "text": "The moment of victory is much too short to live for that and nothing else.",
        "author": "Martina Navratilova",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 112,
        "text": "Gold medals aren't really made of gold. They're made of sweat, determination, and a hard-to-find alloy called guts.",
        "author": "Dan Gable",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 113,
        "text": "Concentration and mental toughness are the margins of victory.",
        "author": "Bill Russell",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 114,
        "text": "The price of success is hard work, dedication to the job at hand, and the determination that whether we win or lose, we have applied the best of ourselves to the task at hand.",
        "author": "Vince Lombardi",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 115,
        "text": "I hated every minute of training, but I said, don't quit. Suffer now and live the rest of your life as a champion.",
        "author": "Muhammad Ali",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 116,
        "text": "Never die easy.",
        "author": "Walter Payton",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 117,
        "text": "No human is limited.",
        "author": "Eliud Kipchoge",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 118,
        "text": "A lot of people run a race to see who is fastest. I run to see who has the most guts.",
        "author": "Steve Prefontaine",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 119,
        "text": "Everybody has a plan until they get punched in the mouth.",
        "author": "Mike Tyson",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 120,
        "text": "He who is not courageous enough to take risks will accomplish nothing in life.",
        "author": "Muhammad Ali",
        "status": "pending",
        "posted_at": None,
    },
]
