"""
quotes_ml.py
─────────────────────────────────────────────────────────────
Central store for all Malayalam quotes used by the YouTube Shorts bot.

Each entry is a dict with these fields:
  {
    "id"        : unique int  (never reuse / reorder),
    "text"      : the quote string,
    "author"    : speaker name in English (used for footage, voice and hashtags),
    "author_ml" : speaker name in Malayalam (spoken + shown on screen),
    "status"    : "pending" | "posted"   ← updated by quote_status.py after upload
    "posted_at" : ISO-8601 UTC string, or None
  }

quote_status.py reads and writes the "status" / "posted_at" fields
directly in this file so everything stays in one place — no separate JSON needed.

To add a new quote: append a new dict with a unique id,
status="pending", and posted_at=None.
Quotes are never re-posted: once every quote is posted the bot stops
with an error until new quotes are added here.
─────────────────────────────────────────────────────────────
"""

DEFAULT_QUOTES = [
    {
        "id": 1,
        "text": "ഒരു ചാമ്പ്യനെ നിർവചിക്കുന്നത് വിജയങ്ങളല്ല, വീഴുമ്പോൾ എങ്ങനെ തിരിച്ചുവരുന്നു എന്നതാണ്.",
        "author": "Serena Williams",
        "author_ml": "സെറീന വില്യംസ്",
        "status": "posted",
        "posted_at": "2026-09-24T08:19:31",
    },
    {
        "id": 2,
        "text": "ആത്മവിശ്വാസവും കഠിനാധ്വാനവും എന്നും നിങ്ങൾക്ക് വിജയം നേടിത്തരും.",
        "author": "Virat Kohli",
        "author_ml": "വിരാട് കോലി",
        "status": "posted",
        "posted_at": "2026-09-26T06:38:40",
    },
    {
        "id": 3,
        "text": "ഒന്നിനും പരിധി നിശ്ചയിക്കരുത്. എത്രത്തോളം സ്വപ്നം കാണുന്നുവോ, അത്രത്തോളം ദൂരം നിങ്ങൾ എത്തും.",
        "author": "Michael Phelps",
        "author_ml": "മൈക്കൽ ഫെൽപ്സ്",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 4,
        "text": "ഇവിടെ ജന്മസിദ്ധമായ കഴിവല്ല, കഠിനാധ്വാനമാണ്. ഇതൊരു അഭിനിവേശമാണ്.",
        "author": "Conor McGregor",
        "author_ml": "കോണർ മക്ഗ്രെഗർ",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 5,
        "text": "വെറുക്കുന്ന കാര്യം പോലും ഇഷ്ടപ്പെടുന്നതുപോലെ ചെയ്യുന്നതാണ് അച്ചടക്കം.",
        "author": "Mike Tyson",
        "author_ml": "മൈക്ക് ടൈസൺ",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 6,
        "text": "നിങ്ങൾ എടുക്കാത്ത ഷോട്ടുകളിൽ നൂറു ശതമാനവും നഷ്ടമാണ്.",
        "author": "Wayne Gretzky",
        "author_ml": "വെയ്ൻ ഗ്രെറ്റ്സ്കി",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 7,
        "text": "തോൽക്കുമെന്ന് നിങ്ങൾ ഭയപ്പെടുന്നുണ്ടെങ്കിൽ, മിക്കവാറും നിങ്ങൾ തോൽക്കും.",
        "author": "Kobe Bryant",
        "author_ml": "കോബി ബ്രയന്റ്",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 8,
        "text": "എനിക്ക് ആരെയും ഭയമില്ല, പക്ഷേ എല്ലാവരെയും ബഹുമാനിക്കുന്നു.",
        "author": "Roger Federer",
        "author_ml": "റോജർ ഫെഡറർ",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 9,
        "text": "മുന്നിലുള്ള മലകളല്ല നിങ്ങളെ തളർത്തുന്നത്, ഷൂസിനുള്ളിലെ ചെറിയൊരു കല്ലാണ്.",
        "author": "Muhammad Ali",
        "author_ml": "മുഹമ്മദ് അലി",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 10,
        "text": "ഓരോ മോശം സാഹചര്യത്തെയും നല്ലൊരു സാഹചര്യമാക്കി മാറ്റുക.",
        "author": "Michael Jordan",
        "author_ml": "മൈക്കൽ ജോർദാൻ",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 11,
        "text": "സ്വപ്നത്തിലെത്താൻ നിങ്ങൾ പോരാടണം. അതിനായി ത്യാഗം ചെയ്യണം, കഠിനാധ്വാനം ചെയ്യണം.",
        "author": "Lionel Messi",
        "author_ml": "ലയണൽ മെസ്സി",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 12,
        "text": "വിജയം എത്ര പ്രയാസമേറിയതാണോ, ജയിക്കുമ്പോഴുള്ള സന്തോഷം അത്രയും വലുതായിരിക്കും.",
        "author": "Pele",
        "author_ml": "പെലെ",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 13,
        "text": "വിജയം ഒരു യാദൃച്ഛികതയല്ല. അത് കഠിനാധ്വാനമാണ്, സ്ഥിരോത്സാഹമാണ്, പഠനമാണ്, ത്യാഗമാണ്. എല്ലാറ്റിനുമുപരി, ചെയ്യുന്ന കാര്യത്തോടുള്ള സ്നേഹമാണ്.",
        "author": "Pele",
        "author_ml": "പെലെ",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 14,
        "text": "വിശ്രമം അവസാനം മതി, ഇടയ്ക്കു വേണ്ട.",
        "author": "Kobe Bryant",
        "author_ml": "കോബി ബ്രയന്റ്",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 15,
        "text": "എനിക്ക് എന്തു ചെയ്യാനാകുമെന്ന് എനിക്കറിയാം, അതുകൊണ്ട് ഞാൻ ഒരിക്കലും എന്നെത്തന്നെ സംശയിക്കാറില്ല.",
        "author": "Usain Bolt",
        "author_ml": "ഉസൈൻ ബോൾട്ട്",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 16,
        "text": "പരിശീലനത്തിന്റെ ഓരോ നിമിഷവും ഞാൻ വെറുത്തിരുന്നു. പക്ഷേ ഞാൻ സ്വയം പറഞ്ഞു, തളരരുത്. ഇപ്പോൾ കഷ്ടപ്പെടുക, ബാക്കി ജീവിതം ഒരു ചാമ്പ്യനായി ജീവിക്കുക.",
        "author": "Muhammad Ali",
        "author_ml": "മുഹമ്മദ് അലി",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 17,
        "text": "സമ്മർദ്ദവും വെല്ലുവിളികളും, എല്ലാ പ്രതികൂല കാര്യങ്ങളും, എനിക്ക് ഉയരാനുള്ള അവസരങ്ങളാണ്.",
        "author": "Kobe Bryant",
        "author_ml": "കോബി ബ്രയന്റ്",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 18,
        "text": "ദിവസങ്ങൾ എണ്ണിയിരിക്കരുത്, ഓരോ ദിവസവും വിലപ്പെട്ടതാക്കുക.",
        "author": "Muhammad Ali",
        "author_ml": "മുഹമ്മദ് അലി",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 19,
        "text": "വിജയം ഒരു യാദൃച്ഛികതയല്ല, അത് ഒരു തിരഞ്ഞെടുപ്പാണ്.",
        "author": "Stephen Curry",
        "author_ml": "സ്റ്റീഫൻ കറി",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 20,
        "text": "എനിക്ക് വിമർശനം ഇഷ്ടമാണ്. അത് നിങ്ങളെ കരുത്തരാക്കും.",
        "author": "LeBron James",
        "author_ml": "ലെബ്രോൺ ജെയിംസ്",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 21,
        "text": "കഠിനാധ്വാനമില്ലാത്ത കഴിവ് ഒന്നുമല്ല.",
        "author": "Cristiano Ronaldo",
        "author_ml": "ക്രിസ്റ്റ്യാനോ റൊണാൾഡോ",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 22,
        "text": "നിങ്ങൾ കളിക്കുന്നത് കാണികൾക്കു വേണ്ടിയല്ല, രാജ്യത്തിനു വേണ്ടിയാണ്.",
        "author": "MS Dhoni",
        "author_ml": "എം എസ് ധോണി",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 23,
        "text": "പതിനായിരം തരം കിക്കുകൾ ഒരിക്കൽ പരിശീലിച്ചവനെ ഞാൻ ഭയപ്പെടുന്നില്ല. ഒരേ കിക്ക് പതിനായിരം തവണ പരിശീലിച്ചവനെയാണ് ഞാൻ ഭയപ്പെടുന്നത്.",
        "author": "Bruce Lee",
        "author_ml": "ബ്രൂസ് ലീ",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 24,
        "text": "നിൽക്കുന്നിടത്തുനിന്ന് തുടങ്ങുക. കയ്യിലുള്ളത് ഉപയോഗിക്കുക. കഴിയുന്നത് ചെയ്യുക.",
        "author": "Arthur Ashe",
        "author_ml": "ആർതർ ആഷ്",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 25,
        "text": "ഒരു മനുഷ്യനും പരിമിതികളില്ല.",
        "author": "Eliud Kipchoge",
        "author_ml": "എലിയുഡ് കിപ്ചോഗെ",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 26,
        "text": "മെച്ചപ്പെടണമെങ്കിൽ, പരാജയം അംഗീകരിക്കാൻ നിങ്ങൾക്ക് കഴിയണം.",
        "author": "LeBron James",
        "author_ml": "ലെബ്രോൺ ജെയിംസ്",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 27,
        "text": "തടസ്സങ്ങൾ നിങ്ങളെ തടയേണ്ടതില്ല. ഒരു മതിലിനു മുന്നിലെത്തിയാൽ തിരിഞ്ഞു നടക്കരുത്. അതിനു മുകളിലൂടെ കയറാനോ, തുളച്ചു കടക്കാനോ, ചുറ്റി പോകാനോ വഴി കണ്ടെത്തുക.",
        "author": "Michael Jordan",
        "author_ml": "മൈക്കൽ ജോർദാൻ",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 28,
        "text": "എന്റെ കരിയറിൽ ഒൻപതിനായിരത്തിലധികം ഷോട്ടുകൾ ഞാൻ പാഴാക്കിയിട്ടുണ്ട്. മുന്നൂറോളം മത്സരങ്ങൾ തോറ്റിട്ടുണ്ട്. ജീവിതത്തിൽ വീണ്ടും വീണ്ടും ഞാൻ പരാജയപ്പെട്ടിട്ടുണ്ട്. അതുകൊണ്ടാണ് ഞാൻ വിജയിക്കുന്നത്.",
        "author": "Michael Jordan",
        "author_ml": "മൈക്കൽ ജോർദാൻ",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 29,
        "text": "ആളുകൾ നിങ്ങൾക്കു നേരെ കല്ലെറിയും, ആ കല്ലുകൾ നിങ്ങൾ നാഴികക്കല്ലുകളാക്കി മാറ്റണം.",
        "author": "Sachin Tendulkar",
        "author_ml": "സച്ചിൻ ടെണ്ടുൽക്കർ",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 30,
        "text": "പരാജയം എനിക്ക് അംഗീകരിക്കാം, എല്ലാവരും എന്തിലെങ്കിലും പരാജയപ്പെടാറുണ്ട്. പക്ഷേ ശ്രമിക്കാതിരിക്കുന്നത് എനിക്ക് അംഗീകരിക്കാനാവില്ല.",
        "author": "Michael Jordan",
        "author_ml": "മൈക്കൽ ജോർദാൻ",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 31,
        "text": "ആശങ്കപ്പെട്ടതുകൊണ്ട് ഒന്നും നേടാനാവില്ല. നന്നായി പരിശീലിക്കുക, കളത്തിലിറങ്ങുക, ഏറ്റവും മികച്ചത് നൽകുക. ബാക്കിയെല്ലാം താനേ ശരിയാകും.",
        "author": "Usain Bolt",
        "author_ml": "ഉസൈൻ ബോൾട്ട്",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 32,
        "text": "എളുപ്പമുള്ള ജീവിതത്തിനായി പ്രാർത്ഥിക്കരുത്. പ്രയാസമേറിയ ജീവിതം നേരിടാനുള്ള കരുത്തിനായി പ്രാർത്ഥിക്കുക.",
        "author": "Bruce Lee",
        "author_ml": "ബ്രൂസ് ലീ",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 33,
        "text": "എത്ര മികച്ചവരായാലും ഇനിയും മെച്ചപ്പെടാം. അതാണ് ഏറ്റവും ആവേശകരമായ കാര്യം.",
        "author": "Tiger Woods",
        "author_ml": "ടൈഗർ വുഡ്സ്",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 34,
        "text": "തോൽവി എന്റെ ശത്രുവല്ല. തോൽക്കുമോ എന്ന ഭയമാണ് എന്റെ ശത്രു.",
        "author": "Rafael Nadal",
        "author_ml": "റാഫേൽ നദാൽ",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 35,
        "text": "നിങ്ങളുടെ സ്നേഹം എന്നെ കരുത്തനാക്കുന്നു, നിങ്ങളുടെ വെറുപ്പ് എന്നെ തടുക്കാനാവാത്തവനാക്കുന്നു.",
        "author": "Cristiano Ronaldo",
        "author_ml": "ക്രിസ്റ്റ്യാനോ റൊണാൾഡോ",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 36,
        "text": "നിങ്ങൾ പിന്മാറുന്ന നിമിഷം, മറ്റൊരാളെ ജയിക്കാൻ അനുവദിക്കുകയാണ്.",
        "author": "Kobe Bryant",
        "author_ml": "കോബി ബ്രയന്റ്",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 37,
        "text": "ചെയ്യാൻ കഴിയാത്തവ, ചെയ്യാൻ കഴിയുന്നവയ്ക്ക് തടസ്സമാകാൻ അനുവദിക്കരുത്.",
        "author": "John Wooden",
        "author_ml": "ജോൺ വുഡൻ",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 38,
        "text": "കരുത്ത് വരുന്നത് വിജയത്തിൽ നിന്നല്ല. നിങ്ങളുടെ പോരാട്ടങ്ങളാണ് കരുത്ത് വളർത്തുന്നത്. പ്രതിസന്ധികളിൽ കീഴടങ്ങില്ലെന്ന് തീരുമാനിക്കുന്നതാണ് യഥാർത്ഥ കരുത്ത്.",
        "author": "Arnold Schwarzenegger",
        "author_ml": "ആർനോൾഡ് ഷ്വാസ്നെഗർ",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 39,
        "text": "സ്വപ്നങ്ങളെ പിന്തുടരൂ, കാരണം സ്വപ്നങ്ങൾ യാഥാർത്ഥ്യമാകും.",
        "author": "Sachin Tendulkar",
        "author_ml": "സച്ചിൻ ടെണ്ടുൽക്കർ",
        "status": "pending",
        "posted_at": None,
    },
    {
        "id": 40,
        "text": "അർപ്പണബോധമാണ് സ്വപ്നങ്ങളെ യാഥാർത്ഥ്യമാക്കുന്നത്.",
        "author": "Kobe Bryant",
        "author_ml": "കോബി ബ്രയന്റ്",
        "status": "pending",
        "posted_at": None,
    },
]
